<?php

use Illuminate\Database\Seeder;

class DocsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('docs')->delete();
        
        \DB::table('docs')->insert(array (
            0 => 
            array (
                'id' => 2,
                'set_name' => 'Code Reader 2700 Configuration Guide',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'code-reader-2700-configuration-guide',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 13:48:26',
                'updated_at' => '2020-06-29 14:36:29',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            1 => 
            array (
                'id' => 3,
                'set_name' => 'Code Reader 900FD Configuration Guide',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'code-reader-900fd-configuration-guide',
                'config_catalog_filter' => 'discontinued',
                'created_at' => '2020-06-29 13:50:25',
                'updated_at' => '2020-06-29 14:35:56',
                'deleted_at' => NULL,
                'status_id' => 2,
            ),
            2 => 
            array (
                'id' => 4,
                'set_name' => 'Code Reader 950 Configuration Guide',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'code-reader-950-configuration-guide',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 13:51:21',
                'updated_at' => '2020-06-29 14:35:30',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            3 => 
            array (
                'id' => 5,
                'set_name' => 'Code Reader 1000XHD Configuration Guide',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'code-reader-1000xhd-configuration-guide',
                'config_catalog_filter' => 'discontinued',
                'created_at' => '2020-06-29 13:52:53',
                'updated_at' => '2020-06-29 14:35:05',
                'deleted_at' => NULL,
                'status_id' => 2,
            ),
            4 => 
            array (
                'id' => 6,
                'set_name' => 'Code Reader 1000 Configuration Guide',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'code-reader-1000-configuration-guide',
                'config_catalog_filter' => 'discontinued',
                'created_at' => '2020-06-29 13:55:34',
                'updated_at' => '2020-06-29 14:34:44',
                'deleted_at' => NULL,
                'status_id' => 2,
            ),
            5 => 
            array (
                'id' => 7,
                'set_name' => 'Code Reader 1100 Configuration Guide',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'code-reader-1100-configuration-guide',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 13:56:10',
                'updated_at' => '2020-06-29 14:34:25',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            6 => 
            array (
                'id' => 8,
                'set_name' => 'Code Reader 1400XHD Configuration Guide',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'code-reader-1400xhd-configuration-guide',
                'config_catalog_filter' => 'discontinued',
                'created_at' => '2020-06-29 13:56:52',
                'updated_at' => '2020-06-29 14:34:06',
                'deleted_at' => NULL,
                'status_id' => 2,
            ),
            7 => 
            array (
                'id' => 9,
                'set_name' => 'Code Reader 1400 Configuration Guide',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'code-reader-1400-configuration-guide',
                'config_catalog_filter' => 'discontinued',
                'created_at' => '2020-06-29 13:57:19',
                'updated_at' => '2020-06-29 14:33:44',
                'deleted_at' => NULL,
                'status_id' => 2,
            ),
            8 => 
            array (
                'id' => 10,
                'set_name' => 'Code Reader 1500 Configuration Guide',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'code-reader-1500-configuration-guide',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 13:58:28',
                'updated_at' => '2020-06-29 14:33:23',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            9 => 
            array (
                'id' => 11,
                'set_name' => 'Code Reader 2300 Configuration Guide',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'code-reader-2300-configuration-guide',
                'config_catalog_filter' => 'discontinued',
                'created_at' => '2020-06-29 14:00:20',
                'updated_at' => '2020-06-29 14:33:01',
                'deleted_at' => NULL,
                'status_id' => 2,
            ),
            10 => 
            array (
                'id' => 12,
                'set_name' => 'Code Reader 2600XHD Configuration Guide',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'code-reader-2600xhd-configuration-guide',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 14:08:18',
                'updated_at' => '2020-06-29 14:32:43',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            11 => 
            array (
                'id' => 13,
                'set_name' => 'Code Reader 2600 Configuration Guide',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'code-reader-2600-configuration-guide',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 14:09:11',
                'updated_at' => '2020-06-29 14:32:23',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            12 => 
            array (
                'id' => 14,
                'set_name' => 'Code Reader 3600DPM Configuration Guide',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'code-reader-3600dpm-configuration-guide',
                'config_catalog_filter' => 'discontinued',
                'created_at' => '2020-06-29 14:09:59',
                'updated_at' => '2020-06-29 14:31:59',
                'deleted_at' => NULL,
                'status_id' => 2,
            ),
            13 => 
            array (
                'id' => 15,
                'set_name' => 'Code Reader 3600 Configuration Guide',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'code-reader-3600-configuration-guide',
                'config_catalog_filter' => 'discontinued',
                'created_at' => '2020-06-29 14:10:53',
                'updated_at' => '2020-06-29 14:31:27',
                'deleted_at' => NULL,
                'status_id' => 2,
            ),
            14 => 
            array (
                'id' => 16,
                'set_name' => 'Code Reader 4400 Configuration Guide',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'code-reader-4400-configuration-guide',
                'config_catalog_filter' => 'discontinued',
                'created_at' => '2020-06-29 14:12:08',
                'updated_at' => '2020-06-29 14:31:08',
                'deleted_at' => NULL,
                'status_id' => 2,
            ),
            15 => 
            array (
                'id' => 17,
                'set_name' => 'Code Reader 5000 Configuration Guide',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'code-reader-5000-configuration-guide',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 14:18:12',
                'updated_at' => '2020-06-29 14:30:52',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            16 => 
            array (
                'id' => 18,
                'set_name' => 'Code Reader 6000 Configuration Guide',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'code-reader-6000-configuration-guide',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 14:19:13',
                'updated_at' => '2020-06-29 14:30:37',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            17 => 
            array (
                'id' => 19,
                'set_name' => 'Code Reader 8000 Configuration Guide',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'code-reader-8000-configuration-guide',
                'config_catalog_filter' => 'discontinued',
                'created_at' => '2020-06-29 14:21:34',
                'updated_at' => '2020-06-29 14:30:20',
                'deleted_at' => NULL,
                'status_id' => 2,
            ),
            18 => 
            array (
                'id' => 20,
                'set_name' => 'Code Reader 8200 Configuration Guide',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'code-reader-8200-configuration-guide',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 14:28:47',
                'updated_at' => '2020-06-29 14:28:47',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            19 => 
            array (
                'id' => 21,
                'set_name' => 'T500 Configuration Guide',
                'industry' => NULL,
                'published' => 1,
                'slug' => 't500-configuration-guide',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 14:29:58',
                'updated_at' => '2020-06-29 14:29:58',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            20 => 
            array (
                'id' => 22,
                'set_name' => 'Code Services Brochure',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'code-services-brochure',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 21:21:51',
                'updated_at' => '2020-06-29 21:22:17',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            21 => 
            array (
                'id' => 23,
                'set_name' => 'Healthcare Product Brochure',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'healthcare-product-brochure',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 21:22:52',
                'updated_at' => '2020-06-29 21:22:52',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            22 => 
            array (
                'id' => 24,
                'set_name' => 'Healthcare Product Line 11x17',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'healthcare-product-line-11x17',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 21:23:25',
                'updated_at' => '2020-06-29 21:23:25',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            23 => 
            array (
                'id' => 25,
                'set_name' => '2700 Epic Integration Guide',
                'industry' => NULL,
                'published' => 1,
                'slug' => '2700-epic-integration-guide',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 21:24:47',
                'updated_at' => '2020-06-29 21:25:15',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            24 => 
            array (
                'id' => 26,
                'set_name' => '2700 Cerner Integration Guide',
                'industry' => NULL,
                'published' => 1,
                'slug' => '2700-cerner-integration-guide',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 21:25:58',
                'updated_at' => '2020-06-29 21:25:58',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            25 => 
            array (
                'id' => 27,
                'set_name' => '2700 Siemens-Mak Integration Guide',
                'industry' => NULL,
                'published' => 1,
                'slug' => '2700-siemens-mak-integration-guide',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 21:26:53',
                'updated_at' => '2020-06-29 21:26:53',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            26 => 
            array (
                'id' => 28,
                'set_name' => '2700 Quadramed Integration Guide',
                'industry' => NULL,
                'published' => 1,
                'slug' => '2700-quadramed-integration-guide',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 21:27:29',
                'updated_at' => '2020-06-29 21:27:29',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            27 => 
            array (
                'id' => 29,
                'set_name' => '2700 Meditech Integration Guide',
                'industry' => NULL,
                'published' => 1,
                'slug' => '2700-meditech-integration-guide',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 21:28:02',
                'updated_at' => '2020-06-29 21:28:02',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            28 => 
            array (
                'id' => 30,
                'set_name' => '2700 Mckesson Paragon Integration Guide',
                'industry' => NULL,
                'published' => 1,
                'slug' => '2700-mckesson-paragon-integration-guide',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 21:28:55',
                'updated_at' => '2020-06-29 21:28:55',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            29 => 
            array (
                'id' => 31,
                'set_name' => '2700 GE Healthcare Integration Guide',
                'industry' => NULL,
                'published' => 1,
                'slug' => '2700-ge-healthcare-integration-guide',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 21:29:49',
                'updated_at' => '2020-06-29 21:29:49',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            30 => 
            array (
                'id' => 32,
                'set_name' => '2700 CPSI Integration Guide',
                'industry' => NULL,
                'published' => 1,
                'slug' => '2700-cpsi-integration-guide',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 21:31:04',
                'updated_at' => '2020-06-29 21:31:04',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            31 => 
            array (
                'id' => 33,
                'set_name' => '2700 AllSripts Eclipsys',
                'industry' => NULL,
                'published' => 1,
                'slug' => '2700-allsripts-eclipsys',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 21:31:39',
                'updated_at' => '2020-06-29 21:31:39',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            32 => 
            array (
                'id' => 34,
                'set_name' => '2700 Quick Start Guide',
                'industry' => NULL,
                'published' => 1,
                'slug' => '2700-quick-start-guide',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 21:32:27',
                'updated_at' => '2020-06-29 21:32:27',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            33 => 
            array (
                'id' => 35,
                'set_name' => '2700 Data Sheet',
                'industry' => NULL,
                'published' => 1,
                'slug' => '2700-data-sheet',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 21:32:50',
                'updated_at' => '2020-06-29 21:32:50',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            34 => 
            array (
                'id' => 36,
                'set_name' => '2700 User Manual',
                'industry' => NULL,
                'published' => 1,
                'slug' => '2700-user-manual',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 21:33:28',
                'updated_at' => '2020-06-29 21:33:28',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            35 => 
            array (
                'id' => 37,
                'set_name' => 'JavaScript Programming Guide User Manual - CR1500 CR1100 CR2700',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'javascript-programming-guide-user-manual-cr1500-cr1100-cr2700',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 21:34:42',
                'updated_at' => '2020-06-29 21:34:42',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            36 => 
            array (
                'id' => 38,
                'set_name' => '2700 Series Scanner Battery FAQ',
                'industry' => NULL,
                'published' => 1,
                'slug' => '2700-series-scanner-battery-faq',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 21:35:15',
                'updated_at' => '2020-06-29 21:35:15',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            37 => 
            array (
                'id' => 39,
                'set_name' => 'A271 & BTDG27 Configuration Control Doc - CR8200 CR950 CR1500 CR1100 CR2700',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'a271-btdg27-configuration-control-doc-cr8200-cr950-cr1500-cr1100-cr2700',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 21:37:36',
                'updated_at' => '2020-06-29 21:37:36',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            38 => 
            array (
                'id' => 40,
                'set_name' => '2700 Competition Comparison',
                'industry' => NULL,
                'published' => 1,
                'slug' => '2700-competition-comparison',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 21:38:42',
                'updated_at' => '2020-06-29 21:38:42',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            39 => 
            array (
                'id' => 41,
                'set_name' => 'CodeShield Data Sheet',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'codeshield-data-sheet',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 21:40:28',
                'updated_at' => '2020-06-29 21:40:28',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            40 => 
            array (
                'id' => 42,
                'set_name' => '7018 Data Sheet',
                'industry' => NULL,
                'published' => 1,
                'slug' => '7018-data-sheet',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 21:47:51',
                'updated_at' => '2020-06-29 21:47:51',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            41 => 
            array (
                'id' => 43,
                'set_name' => '7018 User Manual',
                'industry' => NULL,
                'published' => 1,
                'slug' => '7018-user-manual',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 21:48:57',
                'updated_at' => '2020-06-29 21:48:57',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            42 => 
            array (
                'id' => 44,
                'set_name' => '7000 Series Quick Start Guide',
                'industry' => NULL,
                'published' => 1,
                'slug' => '7000-series-quick-start-guide',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 21:50:07',
                'updated_at' => '2020-06-29 21:50:07',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            43 => 
            array (
                'id' => 45,
                'set_name' => '1100 Healthcare Data Sheet',
                'industry' => NULL,
                'published' => 1,
                'slug' => '1100-healthcare-data-sheet',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 21:56:03',
                'updated_at' => '2020-06-29 21:56:03',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            44 => 
            array (
                'id' => 46,
                'set_name' => 'Retail Brochure',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'retail-brochure',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 21:56:30',
                'updated_at' => '2020-06-29 21:56:30',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            45 => 
            array (
                'id' => 47,
                'set_name' => '1100 Quick Start Guide',
                'industry' => NULL,
                'published' => 1,
                'slug' => '1100-quick-start-guide',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 21:56:58',
                'updated_at' => '2020-06-29 21:56:58',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            46 => 
            array (
                'id' => 48,
                'set_name' => '1100 Data Sheet',
                'industry' => NULL,
                'published' => 1,
                'slug' => '1100-data-sheet',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 21:57:35',
                'updated_at' => '2020-06-29 21:57:35',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            47 => 
            array (
                'id' => 49,
                'set_name' => '1100 User Manual',
                'industry' => NULL,
                'published' => 1,
                'slug' => '1100-user-manual',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 21:58:23',
                'updated_at' => '2020-06-29 21:58:23',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            48 => 
            array (
                'id' => 50,
                'set_name' => 'Retail Product Lineup',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'retail-product-lineup',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 21:59:09',
                'updated_at' => '2020-06-29 21:59:09',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            49 => 
            array (
                'id' => 51,
                'set_name' => 'Manufacturing Product Lineup Brochure',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'manufacturing-product-lineup-brochure',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 22:00:23',
                'updated_at' => '2020-07-08 16:23:11',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            50 => 
            array (
                'id' => 52,
                'set_name' => 'Cortex JPOS User Manual',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'cortex-jpos-user-manual',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 22:09:16',
                'updated_at' => '2020-06-29 22:09:16',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            51 => 
            array (
                'id' => 53,
                'set_name' => 'Cortex OPOS User Manual',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'cortex-opos-user-manual',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 22:10:25',
                'updated_at' => '2020-06-29 22:10:25',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            52 => 
            array (
                'id' => 54,
                'set_name' => 'Allscripts Eclipsys Integration Guide - CR1100, CR1500',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'allscripts-eclipsys-integration-guide-cr1100-cr1500',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 22:13:51',
                'updated_at' => '2020-06-29 22:13:51',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            53 => 
            array (
                'id' => 55,
                'set_name' => 'EPIC Integration Guide - CR1100, CR1500',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'epic-integration-guide-cr1100-cr1500',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 22:14:36',
                'updated_at' => '2020-06-29 23:56:22',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            54 => 
            array (
                'id' => 56,
                'set_name' => 'GE Healthcare Integration Guide - CR1100, CR1500',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'ge-healthcare-integration-guide-cr1100-cr1500',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 22:15:19',
                'updated_at' => '2020-06-29 22:15:19',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            55 => 
            array (
                'id' => 57,
                'set_name' => 'McKesson Paragon Integration Guide - CR1100, CR1500',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'mckesson-paragon-integration-guide-cr1100-cr1500',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 22:16:01',
                'updated_at' => '2020-06-29 22:16:01',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            56 => 
            array (
                'id' => 58,
                'set_name' => 'Meditech Integration Guide - CR1100, CR1500',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'meditech-integration-guide-cr1100-cr1500',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 22:18:40',
                'updated_at' => '2020-06-29 22:18:40',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            57 => 
            array (
                'id' => 59,
                'set_name' => 'Quadramed Integration Guide - CR1100, CR1500',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'quadramed-integration-guide-cr1100-cr1500',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 22:19:50',
                'updated_at' => '2020-06-29 23:56:47',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            58 => 
            array (
                'id' => 60,
                'set_name' => 'Siemens-Mak Integration Guide - CR1100, CR1500',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'siemens-mak-integration-guide-cr1100-cr1500',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 22:20:30',
                'updated_at' => '2020-06-29 22:20:30',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            59 => 
            array (
                'id' => 61,
                'set_name' => 'CPSI Integration Guide - CR1100, CR1500',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'cpsi-integration-guide-cr1100-cr1500',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 22:21:17',
                'updated_at' => '2020-06-29 22:21:17',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            60 => 
            array (
                'id' => 62,
                'set_name' => '1500 Healthcare Data Sheet',
                'industry' => NULL,
                'published' => 1,
                'slug' => '1500-healthcare-data-sheet',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 23:20:09',
                'updated_at' => '2020-06-29 23:20:09',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            61 => 
            array (
                'id' => 63,
                'set_name' => '1500 Industrial Data Sheet',
                'industry' => NULL,
                'published' => 1,
                'slug' => '1500-industrial-data-sheet',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 23:34:33',
                'updated_at' => '2020-06-29 23:34:33',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            62 => 
            array (
                'id' => 64,
                'set_name' => '1500 Quick Start Guide',
                'industry' => NULL,
                'published' => 1,
                'slug' => '1500-quick-start-guide',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 23:35:14',
                'updated_at' => '2020-06-29 23:35:14',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            63 => 
            array (
                'id' => 65,
                'set_name' => '1500 User Manual',
                'industry' => NULL,
                'published' => 1,
                'slug' => '1500-user-manual',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 23:35:41',
                'updated_at' => '2020-06-29 23:36:06',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            64 => 
            array (
                'id' => 66,
                'set_name' => 'Cerner Integration Guide - CR1100, CR1500, CR2700',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'cerner-integration-guide-cr1100-cr1500-cr2700',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 23:39:25',
                'updated_at' => '2020-07-21 16:36:07',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            65 => 
            array (
                'id' => 67,
                'set_name' => '950 Quick Start Guide',
                'industry' => NULL,
                'published' => 1,
                'slug' => '950-quick-start-guide',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 23:42:05',
                'updated_at' => '2020-06-29 23:42:05',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            66 => 
            array (
                'id' => 68,
                'set_name' => 'CR950 User Manual',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'cr950-user-manual',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 23:42:33',
                'updated_at' => '2020-06-29 23:42:33',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            67 => 
            array (
                'id' => 69,
                'set_name' => '5000 Data Sheet',
                'industry' => NULL,
                'published' => 1,
                'slug' => '5000-data-sheet',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 23:46:01',
                'updated_at' => '2020-06-29 23:46:01',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            68 => 
            array (
                'id' => 70,
                'set_name' => '5000 Quick Start Guide',
                'industry' => NULL,
                'published' => 1,
                'slug' => '5000-quick-start-guide',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 23:46:31',
                'updated_at' => '2020-06-29 23:46:31',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            69 => 
            array (
                'id' => 71,
                'set_name' => '5000 User Manual',
                'industry' => NULL,
                'published' => 1,
                'slug' => '5000-user-manual',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 23:47:03',
                'updated_at' => '2020-06-29 23:47:03',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            70 => 
            array (
                'id' => 72,
                'set_name' => '8200 Datasheet',
                'industry' => NULL,
                'published' => 1,
                'slug' => '8200-datasheet',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 23:50:12',
                'updated_at' => '2020-06-29 23:50:12',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            71 => 
            array (
                'id' => 73,
                'set_name' => '2600 Data Sheet',
                'industry' => NULL,
                'published' => 1,
                'slug' => '2600-data-sheet',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 23:52:07',
                'updated_at' => '2020-06-29 23:52:07',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            72 => 
            array (
                'id' => 74,
                'set_name' => '2600 Quick Start Guide',
                'industry' => NULL,
                'published' => 1,
                'slug' => '2600-quick-start-guide',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 23:52:35',
                'updated_at' => '2020-07-09 22:26:30',
                'deleted_at' => '2020-07-09 22:26:30',
                'status_id' => 1,
            ),
            73 => 
            array (
                'id' => 76,
                'set_name' => '2600 User Manual',
                'industry' => NULL,
                'published' => 1,
                'slug' => '2600-user-manual',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 23:53:32',
                'updated_at' => '2020-06-29 23:53:32',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            74 => 
            array (
                'id' => 77,
                'set_name' => 'Epic HIS Integration Guide - CR1000, CR1400, CR2600',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'epic-his-integration-guide-cr1000-cr1400-cr2600',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 23:58:05',
                'updated_at' => '2020-06-29 23:58:05',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            75 => 
            array (
                'id' => 78,
                'set_name' => 'QuadraMed HIS Integration Guide - CR1000, CR1400, CR2600',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'quadramed-his-integration-guide-cr1000-cr1400-cr2600',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-29 23:59:10',
                'updated_at' => '2020-06-29 23:59:10',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            76 => 
            array (
                'id' => 79,
                'set_name' => 'GE Healthcare HIS Integration Guide - CR1000, CR1400, CR2600',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'ge-healthcare-his-integration-guide-cr1000-cr1400-cr2600',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-30 00:00:01',
                'updated_at' => '2020-06-30 00:00:01',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            77 => 
            array (
                'id' => 80,
                'set_name' => 'Allscripts Eclypsis HIS Integration Guide - CR1000, CR1400, CR2600',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'allscripts-eclypsis-his-integration-guide-cr1000-cr1400-cr2600',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-30 00:01:05',
                'updated_at' => '2020-06-30 00:01:05',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            78 => 
            array (
                'id' => 81,
                'set_name' => 'Meditech HIS Quick Start Guide - CR1000, CR1400, CR2600',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'meditech-his-quick-start-guide-cr1000-cr1400-cr2600',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-30 00:02:04',
                'updated_at' => '2020-06-30 00:02:04',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            79 => 
            array (
                'id' => 82,
                'set_name' => 'Siemens MAK Integration Guide - CR1000, CR1400, CR2600',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'siemens-mak-integration-guide-cr1000-cr1400-cr2600',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-30 00:02:52',
                'updated_at' => '2020-06-30 00:02:52',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            80 => 
            array (
                'id' => 83,
                'set_name' => 'CPSI HIS Integration Guide - CR1000, CR1400, CR2600',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'cpsi-his-integration-guide-cr1000-cr1400-cr2600',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-30 00:03:41',
                'updated_at' => '2020-06-30 00:03:41',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            81 => 
            array (
                'id' => 84,
                'set_name' => 'McKesson Paragon BMA Integration Guide - CR1000, CR1400, CR2600',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'mckesson-paragon-bma-integration-guide-cr1000-cr1400-cr2600',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-30 00:04:34',
                'updated_at' => '2020-06-30 00:04:34',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            82 => 
            array (
                'id' => 85,
                'set_name' => 'Cerner Millenium HIS Integration Guide - CR1000, CR1400, CR2600',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'cerner-millenium-his-integration-guide-cr1000-cr1400-cr2600',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-30 00:05:30',
                'updated_at' => '2020-06-30 00:05:30',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            83 => 
            array (
                'id' => 86,
                'set_name' => 'Bluetooth Integration Guide - CR2300, CR2600, CR3600',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'bluetooth-integration-guide-cr2300-cr2600-cr3600',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-30 00:07:20',
                'updated_at' => '2020-06-30 00:07:20',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            84 => 
            array (
                'id' => 87,
                'set_name' => 'MB8 Adapter Installation Instructions',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'mb8-adapter-installation-instructions',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-30 00:08:51',
                'updated_at' => '2020-06-30 00:08:51',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            85 => 
            array (
                'id' => 88,
                'set_name' => '6000 Data Sheet',
                'industry' => NULL,
                'published' => 1,
                'slug' => '6000-data-sheet',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-30 00:09:50',
                'updated_at' => '2020-06-30 00:09:50',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            86 => 
            array (
                'id' => 89,
                'set_name' => '6000 Quick Start Guide',
                'industry' => NULL,
                'published' => 1,
                'slug' => '6000-quick-start-guide',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-30 00:10:19',
                'updated_at' => '2020-06-30 00:10:19',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            87 => 
            array (
                'id' => 90,
                'set_name' => '6000 User Manual',
                'industry' => NULL,
                'published' => 1,
                'slug' => '6000-user-manual',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-06-30 00:10:47',
                'updated_at' => '2020-06-30 00:10:47',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            88 => 
            array (
                'id' => 91,
                'set_name' => 'Code Certifications',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'code-certifications',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-07-07 18:30:06',
                'updated_at' => '2020-07-07 18:31:08',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            89 => 
            array (
                'id' => 92,
                'set_name' => 'CR1500 Healthcare Data Sheet EMEA',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'cr1500-healthcare-data-sheet-emea',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-07-08 15:12:58',
                'updated_at' => '2020-07-08 15:16:59',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            90 => 
            array (
                'id' => 93,
                'set_name' => 'CR1500 Healthcare Data Sheet APAC',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'cr1500-healthcare-data-sheet-apac',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-07-08 15:15:18',
                'updated_at' => '2020-07-08 15:16:27',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            91 => 
            array (
                'id' => 94,
                'set_name' => 'CR1500 Healthcare Data Sheet TAM',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'cr1500-healthcare-data-sheet-tam',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-07-08 15:18:34',
                'updated_at' => '2020-07-08 15:18:34',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            92 => 
            array (
                'id' => 95,
                'set_name' => 'CR950 Data Sheet [French]',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'cr950-data-sheet-french',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-07-08 19:58:01',
                'updated_at' => '2020-07-08 19:58:01',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            93 => 
            array (
                'id' => 96,
                'set_name' => 'CR950 Data Sheet [English]',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'cr950-data-sheet-english',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-07-08 19:59:12',
                'updated_at' => '2020-07-08 19:59:12',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            94 => 
            array (
                'id' => 97,
                'set_name' => 'CR950 Data Sheet [German]',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'cr950-data-sheet-german',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-07-08 20:00:12',
                'updated_at' => '2020-07-08 20:00:12',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            95 => 
            array (
                'id' => 98,
                'set_name' => 'CR950 Data Sheet [Spanish]',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'cr950-data-sheet-spanish',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-07-08 20:01:12',
                'updated_at' => '2020-07-08 20:01:12',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            96 => 
            array (
                'id' => 99,
                'set_name' => 'T500 Quick Start Guide',
                'industry' => NULL,
                'published' => 1,
                'slug' => 't500-quick-start-guide',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-07-08 22:19:40',
                'updated_at' => '2020-07-08 22:19:40',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            97 => 
            array (
                'id' => 100,
                'set_name' => 'CR8200 Interface Control Doc - ICD',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'cr8200-interface-control-doc-icd',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-07-09 20:03:06',
                'updated_at' => '2020-07-09 20:03:06',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            98 => 
            array (
                'id' => 101,
                'set_name' => 'CR8200 CR822x Single Board Integration Guide',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'cr8200-cr822x-single-board-integration-guide',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-07-09 20:05:49',
                'updated_at' => '2020-07-09 20:05:49',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            99 => 
            array (
                'id' => 102,
                'set_name' => 'CR8200 CR822x Dual Board Integration Guide',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'cr8200-cr822x-dual-board-integration-guide',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-07-09 20:07:01',
                'updated_at' => '2020-07-09 20:07:01',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            100 => 
            array (
                'id' => 103,
                'set_name' => 'CR6000 Certifications KCC',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'cr6000-certifications-kcc',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-07-09 23:02:24',
                'updated_at' => '2020-07-09 23:02:24',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            101 => 
            array (
                'id' => 104,
                'set_name' => 'CR2600 Certifications',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'cr2600-certifications',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-07-09 23:04:23',
                'updated_at' => '2020-07-09 23:04:23',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            102 => 
            array (
                'id' => 105,
                'set_name' => 'CR1500 Certifications KCC',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'cr1500-certifications-kcc',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-07-09 23:07:12',
                'updated_at' => '2020-07-09 23:07:12',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            103 => 
            array (
                'id' => 106,
                'set_name' => 'CR2612 Certifications SRRC',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'cr2612-certifications-srrc',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-07-09 23:09:36',
                'updated_at' => '2020-07-09 23:09:36',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            104 => 
            array (
                'id' => 107,
                'set_name' => 'EU Directive Declaration of Conformity',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'eu-directive-declaration-of-conformity',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-07-20 16:02:25',
                'updated_at' => '2020-07-20 16:02:25',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            105 => 
            array (
                'id' => 108,
                'set_name' => 'CR4300 Data Sheet',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'cr4300-data-sheet',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-07-21 16:05:30',
                'updated_at' => '2020-07-21 16:07:26',
                'deleted_at' => NULL,
                'status_id' => 2,
            ),
            106 => 
            array (
                'id' => 109,
                'set_name' => 'CR1100 Universal Stand Quick Start Guide',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'cr1100-universal-stand-quick-start-guide',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-07-21 16:18:21',
                'updated_at' => '2020-07-21 16:18:21',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            107 => 
            array (
                'id' => 110,
                'set_name' => 'Code Reader Universal Stand Quick Start Guide',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'code-reader-universal-stand-quick-start-guide',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-07-21 16:25:11',
                'updated_at' => '2020-07-21 16:25:11',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
            108 => 
            array (
                'id' => 111,
                'set_name' => 'CR2700 McKesson Integration Guide',
                'industry' => NULL,
                'published' => 1,
                'slug' => 'cr2700-mckesson-integration-guide',
                'config_catalog_filter' => 'current',
                'created_at' => '2020-07-21 16:38:47',
                'updated_at' => '2020-07-21 16:38:47',
                'deleted_at' => NULL,
                'status_id' => 1,
            ),
        ));
        
        
    }
}