<?php

use Illuminate\Database\Seeder;

class FeaturesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('features')->delete();
        
        \DB::table('features')->insert(array (
            0 => 
            array (
                'id' => 1,
                'info' => 'Inductive charging eliminates chemical corrosion caused by disinfectants',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 17:55:40',
                'updated_at' => '2020-06-16 17:55:40',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'info' => 'Bluetooth Low Energy 5 for enhanced data security, throughput and transmission range',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 17:55:51',
                'updated_at' => '2020-06-16 17:55:51',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'info' => 'Streamlined case eliminating hard-to-disinfect nooks and crannies',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 17:56:08',
                'updated_at' => '2020-06-16 17:56:08',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'info' => 'PVC-Free CodeShield® plastics stand up to harsh disinfectants',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 17:56:38',
                'updated_at' => '2020-06-16 17:56:38',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'info' => 'Lightweight, ergonomic models in palm and handled configurations',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 17:56:53',
                'updated_at' => '2020-06-16 17:56:53',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'info' => 'Durable, quick-release rechargeable battery cartridges',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 17:57:13',
                'updated_at' => '2020-06-16 17:57:13',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'info' => 'Smart battery shows battery health with a visible fuel gauge',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 17:57:42',
                'updated_at' => '2020-06-16 17:57:42',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'info' => 'Visual, audible, and haptic indicator customization for workflow needs',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 17:58:27',
                'updated_at' => '2020-06-16 17:58:27',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'info' => 'Patented dual-field optics, both high density and wide field in the same unit',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 17:59:46',
                'updated_at' => '2020-06-16 17:59:46',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'info' => 'Patented glare reduction technology for reading barcodes on shiny surfaces',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:00:45',
                'updated_at' => '2020-06-16 18:00:45',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'info' => 'High speed, omnidirectional reading of all 1D, 2D, Postal barcodes.',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:01:31',
                'updated_at' => '2020-06-16 18:01:31',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'info' => 'Multiple programmable buttons for customized workflow processes',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:01:51',
                'updated_at' => '2020-06-16 18:01:51',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'info' => 'Using Bluetooth Dongle pair to any supported Android, iOS, or Windows computer, devices, or tablets',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:02:08',
                'updated_at' => '2020-06-16 18:02:08',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'info' => 'IP65 rating seals out dust and moisture',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:02:27',
                'updated_at' => '2020-06-16 18:02:27',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'info' => 'CortexRM® Remote Management ready',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:03:04',
                'updated_at' => '2020-06-16 18:03:04',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'info' => 'Powerful data management capability with JavaScript',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:03:40',
                'updated_at' => '2020-06-16 18:03:40',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'info' => 'Code Complete service and extended warranty plans',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:04:31',
                'updated_at' => '2020-06-16 18:04:31',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'info' => 'Pair to Bluetooth supported Android, iOS, and Windows mobile devices and tablets',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:04:53',
                'updated_at' => '2020-06-16 18:04:53',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
            'info' => 'Paging button to assist in locating reader (Charger Station with embedded CodeXML® modem option only)',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:05:16',
                'updated_at' => '2020-06-16 18:05:16',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'info' => 'Compatible with Code’s CortexTools2® software configuration utility',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:05:51',
                'updated_at' => '2020-06-16 18:05:51',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'info' => 'CR2600 XHD built-in macro lens',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:06:07',
                'updated_at' => '2020-06-16 18:06:07',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'info' => 'CR2600 XHD High speed, omnidirectional reading of laser-etched barcodes',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:06:19',
                'updated_at' => '2020-06-16 18:06:19',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'info' => 'CR2600 XHD Extreme high density field for reading barcodes as small as 2mil.',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:06:30',
                'updated_at' => '2020-06-16 18:06:30',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'info' => 'Manual or automatic triggering',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:07:06',
                'updated_at' => '2020-06-16 18:07:06',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'info' => 'All-inclusive kits include reader, cable and stand',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:07:20',
                'updated_at' => '2020-06-16 18:07:20',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'info' => 'Reads barcodes on mobile device screens',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:08:19',
                'updated_at' => '2020-06-16 18:08:19',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'info' => 'Customizable Driver License parsing for US, Canada and Colombia',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:09:04',
                'updated_at' => '2020-06-16 18:09:04',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'info' => 'Compatible with Code’s rapid disconnect USB and RS232 Affinity® cables',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:09:45',
                'updated_at' => '2020-06-16 18:09:45',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'info' => 'Efficient power consumption',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:10:56',
                'updated_at' => '2020-06-16 18:10:56',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'info' => 'Level 2 disinfectant-ready housing',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:11:27',
                'updated_at' => '2020-06-16 18:11:27',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'info' => 'CR1100 XHD Enhanced optical platform',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:11:39',
                'updated_at' => '2020-06-16 18:11:39',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'info' => 'CR1100 XHD Reads 1D, 2D and laser-etched marks as small as 2mil',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:11:50',
                'updated_at' => '2020-06-16 18:11:50',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'info' => 'Available in light or dark gray',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:12:17',
                'updated_at' => '2020-06-16 18:12:17',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'info' => 'CR1500 Healthcare PVC-Free CodeShield® plastics stand up to more disinfectants',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:12:31',
                'updated_at' => '2020-06-16 18:12:31',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'info' => 'CR1500 Healthcare Available “plug and play” models for all major Health Information Systems to simplify rollout',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:12:43',
                'updated_at' => '2020-06-16 18:12:43',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'info' => 'CR1500 Healthcare GS1 and HIBC validation and parsing for accurate and efficient data capture',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:12:54',
                'updated_at' => '2020-06-16 18:12:54',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'info' => 'CR1500 Healthcare No exposed metal and seamless design for easier infection control',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:13:04',
                'updated_at' => '2020-06-16 18:13:04',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'info' => 'CR1500 Healthcare Programmable day/night modes to avoid patient disturbance',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:13:14',
                'updated_at' => '2020-06-16 18:13:14',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'info' => 'CR1500 Industrial Optional models optimized to read laser etched, DPM, or high-density codes',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:13:25',
                'updated_at' => '2020-06-16 18:13:25',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'info' => 'CR1500 Industrial Serial interface available for easy Programmable Logic Controller connectivity',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:13:36',
                'updated_at' => '2020-06-16 18:13:36',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'info' => 'CR1500 Industrial Preconfigured kits available for easy connection to major MRP/ERP software packages',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:13:48',
                'updated_at' => '2020-06-16 18:13:48',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'info' => 'CR1000 XHD Built-in macro lens and enhanced optical firmware platform',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:13:59',
                'updated_at' => '2020-06-16 18:13:59',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'info' => 'CR1000 XHD Extreme high-density field',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:14:12',
                'updated_at' => '2020-06-16 18:14:12',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'info' => 'CR1000 XHD Reads 1D, 2D and laser-etched marks as small as 2mil',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:14:25',
                'updated_at' => '2020-06-16 18:14:25',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'info' => 'Hands-free operation or optional trigger reading large, heavy, bulk items',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:14:40',
                'updated_at' => '2020-06-16 18:14:40',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'info' => 'Compact, lightweight and ergonomic design',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:14:54',
                'updated_at' => '2020-06-16 18:14:54',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'info' => 'CR5025 Age Verification Reads all barcoded identification cards',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:15:16',
                'updated_at' => '2020-06-16 18:15:16',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'info' => 'CR5025 Age Verification Does not require a PC or manual management of data',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:15:27',
                'updated_at' => '2020-06-16 18:15:27',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'info' => 'CR5025 Age Verification Audible tone alerts user of underage patron',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:15:51',
                'updated_at' => '2020-06-16 18:15:51',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'info' => 'CR5025 Age Verification May be configured for primary and secondary minimum ages',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:16:13',
                'updated_at' => '2020-06-16 18:16:13',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'info' => 'CR5025 Age Verification Integrates into POS, loyalty, and inventory workflows',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:16:35',
                'updated_at' => '2020-06-16 18:16:35',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'info' => 'Reads laser-etched and dot peen marks',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:16:55',
                'updated_at' => '2020-06-16 18:16:55',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'info' => 'Reads color and low-contrast barcodes',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:17:17',
                'updated_at' => '2020-06-16 18:17:17',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'info' => 'IP54 housing securely protects against dust and debris',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:17:32',
                'updated_at' => '2020-06-16 18:17:32',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'info' => 'Small form factor for operator comfort',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:17:44',
                'updated_at' => '2020-06-16 18:17:44',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'info' => 'Integrated metal clip or hook holder for ease of placement and retrieval',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:17:56',
                'updated_at' => '2020-06-16 18:17:56',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'info' => 'Operates hands-free or handled',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:18:08',
                'updated_at' => '2020-06-16 18:18:08',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'info' => 'Compatible with iPhone 7 and 8',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:18:20',
                'updated_at' => '2020-06-16 18:18:20',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'info' => 'CodeShield® PVC-Free disinfectant-ready plastics',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:18:31',
                'updated_at' => '2020-06-16 18:18:31',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'info' => 'Secure and sealed, protects against damage as well as water and debris',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:18:42',
                'updated_at' => '2020-06-16 18:18:42',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'info' => 'Dragontrail™ screen protector',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:18:54',
                'updated_at' => '2020-06-16 18:18:54',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'info' => 'Quick, hot-swappable 2,700 mAh external battery',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:19:07',
                'updated_at' => '2020-06-16 18:19:07',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
            'info' => 'BatteryTrak application provides real-time battery vitals such as deployment dates, state of health cycle counts and serial numbers (CR7018)',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:19:21',
                'updated_at' => '2020-06-16 18:19:21',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'info' => '5 or 10-bay battery chargers with configurations for any workspace',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:19:34',
                'updated_at' => '2020-06-16 18:19:34',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
            'info' => 'Data pass-through via micro-USB cable (CR7019)',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:19:50',
                'updated_at' => '2020-06-16 18:19:50',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
            'info' => 'Accommodates tap-n-go and SSO workflows (CR7019)',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:20:10',
                'updated_at' => '2020-06-16 18:20:10',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'info' => 'Built in TTL RS232 or USB interface',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:20:44',
                'updated_at' => '2020-06-16 18:20:44',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'info' => 'Free Software Developer’s Kit',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:20:57',
                'updated_at' => '2020-06-16 18:20:57',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'info' => 'Simple to setup and configure',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:21:36',
                'updated_at' => '2020-06-16 18:21:36',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'info' => 'Compact size fits any application',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:21:55',
                'updated_at' => '2020-06-16 18:21:55',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'info' => 'Bright LED aiming mechanism',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:22:25',
                'updated_at' => '2020-06-16 18:22:25',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'info' => 'Attachable illumination blocks for different applications',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:22:40',
                'updated_at' => '2020-06-16 18:22:40',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'info' => 'World-class decoding platform',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:22:54',
                'updated_at' => '2020-06-16 18:22:54',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'info' => 'Imager Only or Imager with Decode Options',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:23:07',
                'updated_at' => '2020-06-16 18:23:07',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'info' => 'Fast boot to start reading right away',
                'icon_class' => NULL,
                'published' => 1,
                'slug' => NULL,
                'created_at' => '2020-06-16 18:23:17',
                'updated_at' => '2020-06-16 18:23:17',
                'deleted_at' => NULL,
                'status_id' => NULL,
            ),
        ));
        
        
    }
}