<?php

use Illuminate\Database\Seeder;

class NewsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('news')->delete();
        
        \DB::table('news')->insert(array (
            0 => 
            array (
                'id' => 1,
                'title' => 'Mars Tohken Solutions Co. Ltd. Makes Investment in Code',
            'page_text' => '<p><strong>Salt Lake City, UT - November 16 2018 –</strong> The Code Corporation, a healthcare industry innovator and leader in image-based barcode scanning technology, announces an expansion of its technology partnership with Mars Tohken Solutions Co., Ltd., headquartered in Shinjuku-ku, Tokyo, Japan (6419.T).&nbsp; The agreement includes an investment in Code by Mars Tohken and a plan to leverage each company’s resources and expertise to expand market reach and invest in new technologies.</p><p>“This partnership has strengthened Code’s position in the marketplace and provides a solid foundation for continued growth of our products and services globally,” said George Powell, President and CEO of Code.&nbsp; “Mars Tohken’s commitment to Code’s innovative technology and intellectual property shows our leadership in providing advanced barcode scanning solutions to the AIDC market.”</p><p>“Our combined relationship with Code reinforces Mars Tohken’s investment in solutions that will enhance our product offerings,” commented Hisashi Kodaira, Managing Director, ADC Business Unit at Mars Tohken Solutions Co., Ltd. “With access to Code’s advanced technology, Mars Tohken has strengthened our position as a leader in the machine vision and barcode scanning markets.”</p><h4><strong>About Code</strong></h4><p>Code&nbsp;is a technology leader in image-based barcode reading solutions. Code designs and manufactures a complete line of image-based barcode reading hardware and software solutions to enhance productivity and exceed customers’ expectations for superior barcode reading performance, ergonomic design, equipment durability, and seamless integration with their operations. Servicing a diverse range of industries and environments, Code’s products are used in critical applications in healthcare, public safety, manufacturing, transportation, retail, and a range of other diverse industries.</p><p>Code\'s worldwide headquarters are located in Salt Lake City, USA, with regional headquarters in China, Singapore, and the Netherlands. For more information, visit <a href="http://www.codecorp.com/">codecorp.com</a>.</p><h4><strong>About Mars Tohken Solutions Co., Ltd.</strong></h4><p>Mars Tohken has been serving the Automatic Identification (AID) industry for more than 40 years, starting with laser scanners for one dimensional barcodes and is one of the pioneers of image-based barcode readers for logistic customers.&nbsp;&nbsp; Mars Tohken maintains an experienced engineering team, developing AID devices such as barcode readers, RFID readers/writers, X-ray inspection devices, and direct/indirect sales networks throughout Japan. Mars Tohken’s worldwide headquarters are located in Tokyo, Japan, with regional headquarters in China and Thailand.&nbsp; For more information, visit <a href="http://www.mars-tohken.co.jp/">mars-tohken.co.jp</a>.</p>',
                'excerpt' => 'Code announces expansion of technology partnership with Mars Tohken. Mars Tohken will invest in Code, and the agreement includes a plan to leverage each company’s expertise to expand market reach and invest in new technologies...',
                'meta_title' => 'Mars Tohken Solutions Co. Ltd. Makes Investment in...',
                'meta_description' => 'Mars Tohken Solutions Co. Ltd. Makes Investment in Code',
                'facebook_title' => 'Mars Tohken Solutions Co. Ltd. Makes Investment in Code on Facebook',
                'facebook_desc' => 'Mars Tohken Solutions Co. Ltd. Makes Investment in Code',
                'twitter_post_description' => 'Mars Tohken Solutions Co. Ltd. Makes Investment in Code',
                'twitter_post_title' => 'Mars Tohken Solutions Co. Ltd. Makes Investment in Code on Twitter',
                'published' => 1,
                'slug' => 'mars-tohken-solutions-co-ltd-makes-investment-in-code',
                'contributor' => NULL,
                'contributor_link' => NULL,
                'contributor_2' => NULL,
                'contributor_2_link' => NULL,
                'created_at' => '2018-11-16 21:35:20',
                'updated_at' => '2020-08-04 21:55:29',
                'deleted_at' => NULL,
                'status_id' => NULL,
                'author_id' => 21,
            ),
            1 => 
            array (
                'id' => 2,
                'title' => 'Code Signs ARBOR Technology as Master Distributor in Asia Pacific',
                'page_text' => '<p><strong>Salt Lake City, UT – December 17, 2018 —</strong> The Code Corporation, a leader in image-based barcode scanning technology, has signed ARBOR as a master distributor for Code barcode readers in the Asia Pacific territory.&nbsp; With offices in Korea, Singapore, China and Taiwan, ARBOR enhances Code’s partner and end user support with local product inventory, expanded sales and application engineering resources.&nbsp; ARBOR’s complementary product portfolio also establishes new opportunities for Code partners to provide end-to-end solutions to their customers.</p><p>“Code has made a difference by delivering high quality products backed by exceptional service,” said George Powell, President and CEO of Code.&nbsp; “ARBOR’s footprint in APAC will allow us to exceed our customers’ expectations, and the expanded product portfolio will help drive new business for Code and ARBOR partners.”</p><p>As a master distributor, ARBOR will now carry an extensive catalog of Code products, shortening order lead times and providing local support in several Asian countries for pre and post-sales engagement.&nbsp; Code’s inventory will be housed alongside ARBOR’s dynamic line of industrial PCs, tablets and mobile computers used in manufacturing, logistics and warehouse applications.</p><p>“With Code’s products as a more integrated part of our portfolio, we will have a very compelling value proposition for the AIDC community,” said Eric Lee, President of ARBOR.&nbsp; “The flexibility of our solutions will create great new opportunities for all our partners.”</p><h4><strong>About Code</strong></h4><p>Code&nbsp;is a technology leader in image-based barcode reading solutions. Code designs and manufactures a complete line of image-based barcode reading hardware and software solutions to enhance productivity and exceed customers’ expectations for superior barcode reading performance, ergonomic design, equipment durability, and seamless integration with their operations. Servicing a diverse range of industries and environments, Code’s products are used in critical applications in healthcare, public safety, manufacturing, transportation, retail, and a range of other diverse industries.</p><p>Code\'s worldwide headquarters are located in Salt Lake City, USA. &nbsp;For more information, visit <a href="https://www.codecorp.com/">codecorp.com</a>.</p><h4><strong>About ARBOR</strong></h4><p>ARBOR Technology Corp., a leader of industrial IoT computing and mobility solution provider. We offer embedded systems, automation products, mobile gateway and handheld computers to vertical markets segments including warehousing, logistics, manufacturing, retail and medical.</p><p>ARBOR Technology is dedicated to become a reliable partner to provide value-added services through outstanding embedded computing, communication and mobility technologies.</p><p>For more information, please visit <a href="https://www.arbor-technology.com/gl/Home">arbor-technology.com</a>.</p>',
                'excerpt' => 'With offices in Korea, Singapore, China and Taiwan, ARBOR enhances Code’s partner and end user support with local product inventory, expanded sales and application engineering...',
                'meta_title' => 'Code Signs ARBOR Technology as Master Distributor...',
                'meta_description' => 'Code Signs ARBOR Technology as Master Distributor in Asia Pacific',
                'facebook_title' => 'Code Signs ARBOR Technology as Master Distributor in Asia Pacific on Facebook',
                'facebook_desc' => 'Code Signs ARBOR Technology as Master Distributor in Asia Pacific',
                'twitter_post_description' => 'Code Signs ARBOR Technology as Master Distributor in Asia Pacific',
                'twitter_post_title' => 'Code Signs ARBOR Technology as Master Distributor in Asia Pacific on Twitter',
                'published' => 1,
                'slug' => 'code-signs-arbor-technology-as-master-distributor-in-asia-pacific',
                'contributor' => NULL,
                'contributor_link' => NULL,
                'contributor_2' => NULL,
                'contributor_2_link' => NULL,
                'created_at' => '2018-12-17 21:36:49',
                'updated_at' => '2020-08-04 18:47:36',
                'deleted_at' => NULL,
                'status_id' => NULL,
                'author_id' => 21,
            ),
            2 => 
            array (
                'id' => 3,
                'title' => 'Medical Device Manufacturers—We Hear You',
            'page_text' => '<h4><strong>Make It Easier to Integrate Barcode Scanning? Done.</strong></h4><figure class="image image-style-side"><img src="/storage/593/cr1100_300x450.jpg"></figure><p><strong>Salt Lake City, UT - February 6, 2019 –</strong> Code, an innovator in healthcare automation and mobile technology, is featuring its <a href="https://www.codecorp.com/portfolio-items/code-reader-1100/">new CR1100 compact barcode reading system</a> at the Health Information Management Systems Society (HIMSS) show in Orlando next week. The CR1100 features years of healthcare barcode reading experience combined with the latest image processing technology in a tiny package that easily fits into a variety of medical devices.</p><p>“The CR1100 is different than most embedded barcode readers because it gives full scanner functionality – reading, audible feedback, plug-and-play interface cables – in the smallest product possible,” said Garrett Russell, Vice President of Marketing and North American Sales. “Manufacturers have enough to worry about with their own technology, so we made ours stress free for them to integrate.”</p><p>For nearly 20 years, Code has dealt with the toughest scanning challenges in hospitals, pharmacies, and labs, reading even the most damaged barcodes when no one else could.&nbsp;This specialized knowledge has been combined with patented functionality to create the CR1100: a reader well suited for healthcare applications.</p><p>Code has taken additional steps to shrink the footprint of the technology without sacrificing performance. The result is a fully enclosed, super small scanner with integrated mounting features and plug-and-play interface cables to allow medical device manufacturers to add barcode reading functionality to their systems quickly. A powerful JavaScript platform makes it easy to customize the CR1100 to interface with virtually any host.</p><p>“Code has a long history of working closely with device manufacturers to optimize data capture,” said Hong Ji, Program Manager. “The CR1100 continues our dedication to providing flexible solutions for these customers without having them settle for less than the best reading performance.”</p>',
                'excerpt' => 'Code will feature new CR1100 compact barcode reader next week at HIMSS show. The CR1100 packs years of healthcare barcode reading experience and the latest image-processing tech into a tiny package...',
                'meta_title' => 'Make It Easier to Integrate Barcode Scanning?  Don...',
                'meta_description' => 'Salt Lake City, UT - February 6, 2019 – Code, an innovator in healthcare automation and mobile techn...',
                'facebook_title' => 'Make It Easier to Integrate Barcode Scanning?  Done. on Facebook',
                'facebook_desc' => 'Salt Lake City, UT - February 6, 2019 – Code, an innovator in healthcare automation and mobile techn...',
                'twitter_post_description' => 'Salt Lake City, UT - February 6, 2019 – Code, an innovator in healthcare automation and mobile techn...',
                'twitter_post_title' => 'Make It Easier to Integrate Barcode Scanning?  Done. on Twitter',
                'published' => 1,
                'slug' => 'medical-device-manufacturers-we-hear-you',
                'contributor' => NULL,
                'contributor_link' => NULL,
                'contributor_2' => NULL,
                'contributor_2_link' => NULL,
                'created_at' => '2019-02-16 21:38:02',
                'updated_at' => '2020-08-04 21:58:39',
                'deleted_at' => NULL,
                'status_id' => NULL,
                'author_id' => 21,
            ),
            3 => 
            array (
                'id' => 4,
                'title' => 'Duplicate',
            'page_text' => '<p>Feb 11, 2019</p><p><strong>Salt Lake City, UT - February 11, 2019 –</strong> Code, an innovator in healthcare automation and mobile technology, is bringing some additional excitement to the Healthcare Information Management Systems Society (HIMSS) show in Orlando with the release of the CR7000 series healthcare mobile battery case.&nbsp; The durable protector for the iPhone 7 and 8 completely shields your valuable electronics while maximizing uptime with its quick-swappable battery, all in a compact package made to stand up to the toughest disinfecting chemicals.</p><p>“Health systems should be able to take full advantage of the benefits of mobile devices without having to sacrifice efficiency or infection control,” said George Powell, CEO and President of Code.&nbsp; “With the ruggedness and extra power of the CR7018, hospitals can recognize the full potential of a mobile workforce.”</p><p>Constructed with market-leading CodeShield® plastics and Dragontrail™ glass, <a href="https://github.com/ap-coder/tojekyll/blob/master/portfolio-items/code-reader-7018">the CR7018 completely safeguards the iPhone 7 and 8 in an IP54-sealed enclosure.</a>&nbsp; The quick-swap battery more than doubles the runtime of the iPhone, with a built-in gauge to let nurses know when it’s time to grab more power.&nbsp; With the push of a button, they can easily exchange for a fully-charged battery from one of Code’s enterprise chargers, all without removing the iPhone from the protective case.&nbsp; Users can rapidly charge up to 10 batteries at a time so full power is always on-hand, and a variety of mounting configurations means chargers are easily accessible wherever they are needed.</p><p>The CR7018 also comes with the essential tools that hospital IT needs for easy device management.&nbsp; BatteryTrak™ gives administrators visibility to the age of their batteries and helps them plan appropriately for replacements.&nbsp; <i>Code Complete</i>™ provisioning and deployment services are also available to help reduce the strain on internal resources.</p><p>“As hospitals roll out their iPhone clinical communication strategy, they’ve typically settled for flimsy consumer cases to provide some level of protection to their investment,” said Jennifer Braun, Mobile Program Manager. &nbsp;“Code has packaged decades of healthcare technology know-how into the CR7018, so now hospitals don’t have to settle.”</p>',
            'excerpt' => 'Salt Lake City, UT - February 11, 2019 – Code, an innovator in healthcare automation and mobile technology, is bringing some additional excitement to the Healthcare Information Management Systems Society (HIMSS) show in Orlando with the release of the CR7000 series healthcare mobile battery case. The durable protector for the iPhone 7 and 8 completely shields your valuable electronics while...',
                'meta_title' => 'Code releases powered protection for iPhone 7 & 8',
                'meta_description' => 'Code releases powered protection for iPhone 7 & 8',
                'facebook_title' => 'Code releases powered protection for iPhone 7 & 8 on Facebook',
                'facebook_desc' => 'Code releases powered protection for iPhone 7 & 8',
                'twitter_post_description' => 'Code releases powered protection for iPhone 7 & 8',
                'twitter_post_title' => 'Code releases powered protection for iPhone 7 & 8 on Twitter',
                'published' => 1,
                'slug' => 'duplicate',
                'contributor' => NULL,
                'contributor_link' => NULL,
                'contributor_2' => NULL,
                'contributor_2_link' => NULL,
                'created_at' => '2019-02-11 21:38:49',
                'updated_at' => '2020-08-03 22:49:47',
                'deleted_at' => '2020-08-03 22:49:47',
                'status_id' => NULL,
                'author_id' => 21,
            ),
            4 => 
            array (
                'id' => 5,
                'title' => 'Improve Patient Safety with Code’s Smart Battery Case',
                'page_text' => '<p>May 27, 2019</p><h4><strong>Shipping Powered Protection for Patients and iPhone</strong></h4><figure class="image image-style-side"><img src="https://camo.githubusercontent.com/6aba26dae8a6665b908234586c450dad9a853ae3/68747470733a2f2f636f6465636f72702e636f6d2f77702d636f6e74656e742f75706c6f6164732f323032302f30362f4352373031382d6375742d6f75742e706e67" alt="CR7018-cut-out"></figure><p><strong>Salt Lake City, UT – May 27, 2019 –</strong> Code, an innovator in healthcare automation and mobile technology, is shipping the market’s first fully-enclosed battery case for the iPhone 7 and 8. <a href="https://github.com/ap-coder/tojekyll/blob/master/portfolio-items/code-reader-7018">Designed for healthcare, the CR7018 mobile case</a> is exclusively built with PVC-free CodeShield® disinfectant-ready plastics and Dragontrail™ glass. This completely sealed enclosure not only protects the iPhone from repeated chemical wipe downs, but promotes a higher level of patient safety, removing access for germs to hitch a ride from one patient room to another. It’s the ultimate protection.</p><figure class="image image-style-side"><img src="https://camo.githubusercontent.com/d8269a4e9fc4fa605df0778f2f861cebadf4b978/68747470733a2f2f636f6465636f72702e636f6d2f77702d636f6e74656e742f75706c6f6164732f323032302f30362f4352373031382d6375742d6f75742d6261636b2d7765622e706e67" alt="CR7018-cut-out-back-web"></figure><p>According to the CDC, every day, one in 31 patients will contract an infectious disease during a hospital visit. Many of these are caused by strong bacteria that can lead to serious complications like sepsis, or even death1.&nbsp; Mobile technology at the point of care has historically been unable to stand up to strict cleaning and disinfecting processes.&nbsp; This meant devices would get damaged under chemical exposure, or worse, they weren’t being cleaned properly, contributing to the spread of infectious disease.&nbsp; The CR7018 solves this problem by protecting the mobile devices from damage while promoting easy, thorough disinfection.</p><p>“The CR7000 allows healthcare leaders to protect their investments but more importantly their patients,” said Jennifer Braun, Mobile Program Manager. “Healthcare facilities have been searching for an enterprise mobility solution that accommodates their workflows and meets infection control standards—they’re looking for the CR7000 product line.”</p>',
                'excerpt' => 'Code ships healthcare\'s first fully enclosed battery case for the iPhone 7 and 8. The CR7018 mobile case is built with exclusive PVC-free CodeShield® disinfectant-ready...',
                'meta_title' => 'Improve Patient Safety with Code’s Smart Battery C...',
                'meta_description' => 'Improve Patient Safety with Code’s Smart Battery Case Shipping powered protection for patients and i...',
                'facebook_title' => 'Improve Patient Safety with Code’s Smart Battery Case on Facebook',
                'facebook_desc' => 'Improve Patient Safety with Code’s Smart Battery Case Shipping powered protection for patients and i...',
                'twitter_post_description' => 'Improve Patient Safety with Code’s Smart Battery Case Shipping powered protection for patients and i...',
                'twitter_post_title' => 'Improve Patient Safety with Code’s Smart Battery Case on Twitter',
                'published' => 1,
                'slug' => 'improve-patient-safety-with-codes-smart-battery-case',
                'contributor' => NULL,
                'contributor_link' => NULL,
                'contributor_2' => NULL,
                'contributor_2_link' => NULL,
                'created_at' => '2019-05-27 21:39:41',
                'updated_at' => '2020-08-04 21:35:21',
                'deleted_at' => NULL,
                'status_id' => NULL,
                'author_id' => 21,
            ),
            5 => 
            array (
                'id' => 6,
                'title' => 'Introducing the New Standard for Medical Barcode Scanning—CR2700',
            'page_text' => '<h4><strong>The Healthcare Barcode Leader Does it Again</strong></h4><figure class="image image-style-side"><img src="/storage/588/cr2700-300w.jpg"></figure><p><strong>Salt Lake City, UT – June 03, 2019 —</strong> Code, an innovator in healthcare automation and mobile technology, is launching its highly anticipated next generation of wireless handheld barcode readers.&nbsp;<strong> </strong><a href="https://www.codecorp.com/portfolio-items/code-reader-2700/"><strong>The CR2700 is the new gold standard for healthcare barcode scanning,</strong></a><strong> delivering unmatched reading performance in a seamless package, with inductive charging, to support even the most rigorous infection control practices.</strong></p><p>“We are excited to roll out these new Code scanners,” said Joseph Hooks, Director, CTO, and CISO at Children’s Hospital of The King’s Daughters in Norfolk, Virginia. “Our infection control processes are very strict, and we need technology designed to withstand repeated disinfecting.”</p><p>With the addition of inductive charging, Code has eliminated all exposed metal on its new product, and created a sleek design with fewer nooks, gaps and cutouts to promote easier cleaning. CodeShield® plastics and the only IP65 rating in the healthcare market give the CR2700 unrivaled ruggedness to survive the daily rigors of hospital use.</p><p><strong>The CR2700 features Bluetooth® 5,</strong> enabling it to securely connect to a variety of devices with ease.&nbsp; By additionally implementing a Low Energy radio (BLE), Code has extended the battery life on the new reader to further minimize downtime during shifts.&nbsp; A built-in gauge tells users when it is time to change the battery, which can quickly be swapped for a fresh one, getting nurses right back to caring for patients.&nbsp; Available in either palm or handled form factors, and with a variety of mounting options for chargers, hospitals can choose the exact configuration they require to meet the needs of their unique environments.</p><figure class="image image-style-side"><img src="/storage/587/cr2700_patient_scan_300x300.jpg"></figure><p><strong>The state-of-the-art CR2700 is also packed with a slew of features to help hospital IT efficiently deploy and manage their scanners.</strong>&nbsp; With the ability to track service start dates and vital battery statistics, such as charge frequency and remaining life, the CR2700 provides a new level of asset visibility and replacement planning.&nbsp; Code is ready to assist with installation and training options to ensure a smooth rollout, and Code Complete protection plans practically eliminate downtime.</p><p>“The CR2700 is a purpose-built scanner for healthcare and is not adapted from a retail or commercial product like others on the market,” said Hong Ji, Handheld Program Manager. “As a fourth-generation product, it incorporates over fifteen years of feedback from nurses, doctors and hospital IT staff into a design that truly embodies the voice of the healthcare community.”</p>',
                'excerpt' => 'This next-generation wireless barcode reader delivers unmatched performance and inductive charging in a seamless package—to support even the most rigorous infection control practices...',
                'meta_title' => 'Introducing the New Standard for Medical Barcode S...',
                'meta_description' => 'The Market Leader Does It Again–Introducing the New Standard for Medical Barcode Scanning...',
                'facebook_title' => 'Introducing the New Standard for Medical Barcode Scanning on Facebook',
                'facebook_desc' => 'The Market Leader Does It Again–Introducing the New Standard for Medical Barcode Scanning...',
                'twitter_post_description' => 'The Market Leader Does It Again–Introducing the New Standard for Medical Barcode Scanning...',
                'twitter_post_title' => 'Introducing the New Standard for Medical Barcode Scanning on Twitter',
                'published' => 1,
                'slug' => 'introducing-the-new-standard-for-medical-barcode-scanning-cr2700',
                'contributor' => NULL,
                'contributor_link' => NULL,
                'contributor_2' => NULL,
                'contributor_2_link' => NULL,
                'created_at' => '2019-06-03 21:40:26',
                'updated_at' => '2020-08-04 21:27:56',
                'deleted_at' => NULL,
                'status_id' => NULL,
                'author_id' => 21,
            ),
            6 => 
            array (
                'id' => 7,
                'title' => 'Novant Health Calls CortexDecoder for Epic Rover \'Life Changing\'',
                'page_text' => '<p>Code, an innovator in healthcare automation and mobile technology, is excited to recognize Novant Health’s commitment to improved mobile healthcare scanning with the implementation of Code’s scanning solution CortexDecoder for Epic Rover. Serving communities across the Southeast, Novant Health is a multi-state integrated network of physician clinics, outpatient centers and hospitals that delivers a seamless healthcare experience to its community members. The Novant Health network consists of nearly 30,000 team members who provide care at 640 locations, including 15 medical centers and hundreds of outpatient facilities and physicians clinics. Headquartered in North Carolina, Novant Health serves more than five million patients annually.</p><figure class="image"><img src="https://camo.githubusercontent.com/e4e935f7cb0201b4462b6c2ad84d7befcab2c922/68747470733a2f2f636f6465636f72702e636f6d2f77702d636f6e74656e742f75706c6f6164732f323032302f30362f636f727465782d6465636f6465722d6c6f676f2d636f6c6f722e706e67" alt="cortex-decoder-logo-color"></figure><p><a href="https://www.codecorp.com/software/"><strong>Code’s CortexDecoder is a software-based barcode scanning solution</strong></a>&nbsp;that was chosen for integration into Epic Rover because it provides users enterprise-grade, barcode scanning strength – using only the camera on an iOS device. CortexDecoder can scan over 40 different barcode symbologies, allowing healthcare workers to seamlessly move from one workflow to another.</p><figure class="image image-style-side"><img src="https://camo.githubusercontent.com/3ac61264128e6a188cf980f82fad513603a8db68/68747470733a2f2f636f6465636f72702e636f6d2f77702d636f6e74656e742f75706c6f6164732f323032302f30362f696d6167652d362e706e67" alt=""></figure><p>Novant is seeing excellent acceptance and integration of the technology. Software-enabled barcode scanning of patient wristbands to access medical records coupled with the ability to scan and verify medications helps to significantly reduce errors and improve patient safety – making soft-scanning a huge win for both the medical staff and their patients.</p><p>According to Jill McKinney, Novant Health Director of Clinical Informatics, “Using the mobile devices to scan and administer medication has been ‘life changing’.” She reports that staff members are thrilled with the ease of use and effectiveness provided by the CortexDecoder.</p><p>“We are excited to join forces with Novant Health in improving healthcare in the Southeast,” said Garrett Russell, Vice President of Sales and Marketing for Code. “The healthcare industry has been waiting for the next ‘big thing’ and combining CortexDecoder with Epic Rover is it. This is a huge step for the industry, and Novant Health is a leader in the movement for this mobility revolution.”</p><p>Novant Health is an integrated system of physician practices, hospitals, outpatient centers, and more – each element committed to delivering a remarkable healthcare experience for you and your family. With world-class technology, personal connections, and care that’s easier to access and understand, Novant Health is with patients every step of the way on their journey to health and wellness. Novant Health operates facilities in North Carolina, South Carolina, and Virginia.</p><p>Interested in seeing the full line of&nbsp;<a href="https://www.codecorp.com/healthcare-datacapture/">healthcare specific data capture solutions from Code?</a>&nbsp;Contact us and&nbsp;<a href="https://www.codecorp.com/healthcare-datacapture/#demo">schedule a demo</a>&nbsp;for your team and understand why Code continues to be the nurse favorite and number one provider of barcode scanning solutions for the healthcare industry. Have questions or comments? Feel free to leave them below we love your feedback!</p>',
                'excerpt' => 'Serving the Southeast, Novant Health is a multi-state network of physician clinics, outpatient centers and hospitals that delivers a seamless healthcare experience to its community...',
                'meta_title' => 'Novant Health Calls CortexDecoder for Epic Rover -...',
                'meta_description' => 'Code, an innovator in healthcare automation and mobile technology, is excited to recognize Novant He...',
                'facebook_title' => 'Novant Health Calls CortexDecoder for Epic Rover - Life Changing on Facebook',
                'facebook_desc' => 'Code, an innovator in healthcare automation and mobile technology, is excited to recognize Novant He...',
                'twitter_post_description' => 'Code, an innovator in healthcare automation and mobile technology, is excited to recognize Novant He...',
                'twitter_post_title' => 'Novant Health Calls CortexDecoder for Epic Rover - Life Changing on Twitter',
                'published' => 1,
                'slug' => 'novant-health-calls-cortexdecoder-for-epic-rover-life-changing',
                'contributor' => NULL,
                'contributor_link' => NULL,
                'contributor_2' => NULL,
                'contributor_2_link' => NULL,
                'created_at' => '2019-07-09 21:41:15',
                'updated_at' => '2020-08-04 21:08:18',
                'deleted_at' => NULL,
                'status_id' => NULL,
                'author_id' => 21,
            ),
            7 => 
            array (
                'id' => 8,
                'title' => 'New Appointment of Interim President & CEO for Code',
                'page_text' => '<p>After 20 years of service as President &amp; CEO,&nbsp;George Powell&nbsp;has left the company.&nbsp;The Board of Directors has appointed&nbsp;Barclay McFadden III&nbsp;as interim CEO and&nbsp;Dennis Kaill&nbsp;as interim President.&nbsp; Mr. McFadden will also continue as Chairman of the Code Board of Directors.</p><p>Mr. McFadden has been Code\'s Chairman since 2001.&nbsp; Before joining Code, Mr. McFadden served as the Chairman and CEO of Stow Mills,&nbsp;Chesterfield, NH&nbsp;from 1976 to 1997. &nbsp;Mr. McFadden also serves as Chairman of American Stainless,&nbsp;Cheraw, SC, which sells stainless steel products to industrial companies in the Southeast.</p><p>Mr. Kaill has been on Code\'s Board of Directors since 2015.&nbsp; He has more than 17 years of senior leadership experience within the software and technology sectors. &nbsp;Prior to joining Code\'s board he spent 10 years as President/Managing Director of Microscan Systems, an international bar code technology company, where he took Microscan from a market and profit share laggard to a leadership position.</p><p>"George and I, along with our experienced and professional associates, took Code from a near bankrupt internet startup to a leading barcode technology company, especially within Healthcare," said&nbsp;Barclay McFadden III, Chairman of the Board.&nbsp; "I wish George the best in his future&nbsp;endeavors."</p><p>"Before I joined Code\'s board, Code was a key partner of&nbsp;Microscan," says&nbsp;Dennis Kaill, Interim President. "My familiarity with the company, its products and management team will make for a smooth transition."</p><p>"I enjoyed my time at Code, and I wish nothing but the best for the future of the company, and leave the business with a strong foundation and strong management team in place," stated&nbsp;George Powell.</p><p>Vice President of Sales,&nbsp;North America&nbsp;&amp; Global Marketing,&nbsp;Garrett Russell&nbsp;added, "Code has become a leading provider of barcode scanning solutions during the past 10 years that I have been with Code.&nbsp; I look forward to working with Barclay, Dennis and our future CEO as we execute on our long-term strategy."</p><p>Click here to view this&nbsp;<a href="https://www.prnewswire.com/news-releases/code-corporation-announces-appointment-of-president--ceo-300884515.html?tc=eml_cleartime">press release on PRNewswire.</a>&nbsp;For questions or comments, please reach out to&nbsp;<a href="mailto:leslie.bryant@codecorp.com">Leslie Bryant,</a>&nbsp;Marketing Manager and Media Contact.</p>',
                'excerpt' => 'Code\'s Board of Directors appoints Barclay McFadden III as interim CEO and Dennis Kaill as interim President. Mr. McFadden will also continue as Chairman of the Code Board of Directors. Mr. McFadden has been Code\'s Chairman since 2001. Before joining Code, Mr. McFadden served as the Chairman and CEO of Stow Mills, Chesterfield...',
                'meta_title' => 'NEW APPOINTMENT OF INTERIM PRESIDENT & CEO FOR COD...',
                'meta_description' => 'The Board of Directors has appointed Barclay McFadden III as interim CEO and Dennis Kaill as interim President. ',
                'facebook_title' => 'NEW APPOINTMENT OF INTERIM PRESIDENT & CEO FOR CODE on Facebook',
                'facebook_desc' => 'The Board of Directors has appointed Barclay McFadden III as interim CEO and Dennis Kaill as interim President. ',
                'twitter_post_description' => 'The Board of Directors has appointed Barclay McFadden III as interim CEO and Dennis Kaill as interim President. ',
                'twitter_post_title' => 'NEW APPOINTMENT OF INTERIM PRESIDENT & CEO FOR CODE on Twitter',
                'published' => 1,
                'slug' => 'new-appointment-of-interim-president-ceo-for-code',
                'contributor' => NULL,
                'contributor_link' => NULL,
                'contributor_2' => NULL,
                'contributor_2_link' => NULL,
                'created_at' => '2019-07-15 21:41:43',
                'updated_at' => '2020-08-04 20:59:46',
                'deleted_at' => NULL,
                'status_id' => NULL,
                'author_id' => 21,
            ),
            8 => 
            array (
                'id' => 9,
                'title' => 'Code Corporation Selects Kent Hansen to Fill CEO position',
                'page_text' => '<figure class="image image-style-side"><img src="/storage/579/kent_219x300.jpg"></figure><p><strong>Salt Lake City, UT - October 7, 2019 —</strong> Code Corporation, in conjunction with TachyonIQ, is excited to announce the appointment of Kent L. Hansen as the company’s new CEO. Before joining Code Corporation, Kent was the former President and partner of CA Engineering where he spearheaded growth and developed the strategic direction for the company. Under his leadership, the company grew profitable revenue over 700 percent and developed strategic partner relationships both internationally and domestically. Previous to his work at CA Engineering, Kent was a Senior Director at 3Com where he led the OEM team and additionally grew revenue to over $700 million.</p><p>With over 30 years’ experience in all aspects of running a technology business, Kent brings with him a diverse background of valuable expertise to propel the Code brands, products, and technology beyond projected growth in the data capture industry.</p><p>Kent earned a Bachelor of Science degree in Finance from the University of Utah and also completed the Executive Education Management Program from The Wharton School. Outside of work, Kent enjoys spending time with his wife, Tami, and their three children. You can often find him enjoying the beautiful Utah outdoors boating, skiing, and perfecting his golf game.</p><p>Code’s industry-innovating product portfolio includes both hardware and software image-based data capture solutions that spotlight its powerful decoding algorithm. Code designs and manufactures a complete line of barcode reading hardware and software solutions servicing a diverse range of industries and environments. Code’s scanning technology has been solving critical workflow problems for over 20 years in industries like healthcare, government, manufacturing, transportation, retail, and more. Its subsidiary, TachyonIQ, focuses on the development of its world-class, barcode-reading software used throughout markets as diverse as robotics, logistics, retail, and manufacturing. The products and software technology continue to have a growing global presence as businesses everywhere recognize and harness the power and use of data capture.</p><blockquote><p>According to Code Chairman of the Board of Directors Barclay McFadden III, “Our key criteria was to find an individual who will provide the leadership to build Code into a world-class organization.&nbsp;Kent has demonstrated the ability to do just that throughout his career. We also sought an individual whose management style encourages a collaborative working environment.&nbsp;Kent brings strong product management, sales, OEM, contract manufacturing, and financial expertise to Code.”</p><p>Vice President of Sales, North America &amp; Global Marketing, Garrett Russell added, “Code has become a leading provider of barcode scanning solutions during the last two decades. I look forward to the changes and growth that Kent will help us achieve and the innovations that will be inspired by his leadership.”</p><p>Newly appointed CEO, Kent Hansen added, “I couldn’t be more excited to join this amazing team of incredibly talented and smart individuals who make up the Code family–including our extended family of distributors and resellers. Together we will continue to offer customers not only the most innovative data capture technology available but also the most creative product solutions the industry has ever seen. I am happy to champion the Code brands in this new chapter and look forward to many more years of not only business success, but exceeding our customer’s expectations.”</p></blockquote><h4><strong>About Code and TachyonIQ</strong></h4><p>&nbsp;For over 20 years, Code has been an industry pioneer, leader, and champion for data capture innovation. By crafting and continuing to perfect its unique decoding algorithms, Code’s scanning technology consistently delivers unparalleled, image-based scanning and decoding performance industries depend on worldwide. Code designs and manufactures a complete line of market-leading data capture solutions that include both hardware and software products. Code products are not only valued for providing a consistent level of workflow efficiency year after year, but also for their ergonomic design, durability, ease of customization, and seamless integration.</p><p>A division of Code Corporation, TachyonIQ is an International software developer of image processing algorithms, including barcode decoding, that is used globally in every industry and application where accurate, rapid data capture is used for mission-critical functions and business growth in the IoT and Industry 4.0.</p>',
                'excerpt' => 'Before joining Code, Kent was President and partner of CA Engineering, spearheading growth and the company\'s strategic direction. Under his leadership, the company grew profitable revenue by over 700 percent...',
                'meta_title' => 'Code Corporation selects Kent Hansen to fill CEO p...',
                'meta_description' => 'Code Corporation selects Kent Hansen to fill CEO position',
                'facebook_title' => 'Code Corporation selects Kent Hansen to fill CEO position on Facebook',
                'facebook_desc' => 'Code Corporation selects Kent Hansen to fill CEO position',
                'twitter_post_description' => 'Code Corporation selects Kent Hansen to fill CEO position',
                'twitter_post_title' => 'Code Corporation selects Kent Hansen to fill CEO position on Twitter',
                'published' => 1,
                'slug' => 'code-corporation-selects-kent-hansen-to-fill-ceo-position',
                'contributor' => NULL,
                'contributor_link' => NULL,
                'contributor_2' => NULL,
                'contributor_2_link' => NULL,
                'created_at' => '2019-10-07 21:43:46',
                'updated_at' => '2020-08-04 20:49:18',
                'deleted_at' => NULL,
                'status_id' => NULL,
                'author_id' => 21,
            ),
            9 => 
            array (
                'id' => 10,
                'title' => 'Jana Buck Promoted to Code Corporation\'s Chief Operations Officer',
                'page_text' => '<figure class="image image-style-side"><img src="/storage/583/jana_200x200.jpg"></figure><p>Code Corporation announced recently that Jana Buck has been promoted to Chief Operations Officer. She has been with Code for 17 years serving most recently as the Vice President of Operations at the headquarters in Draper, Utah.&nbsp;</p><p>Before joining Code, Jana studied Pre-Med at Brigham Young University in Provo, Utah. Originally from Brookings, Oregon, she resides in Cottonwood Heights, Utah with her adorable seven- pound Yorkie Coco.</p><blockquote><p>Commenting on her time with the company, Buck says, “I’ve enjoyed working for Code for almost two decades surrounded by an intelligent, hardworking, and motivated team who have been instrumental in Code’s success.” When asked about her plans in this position, she added, “With this promotion, I can drive business performance and operational excellence throughout the organization and help take Code to the next level.”</p><p>Kent Hansen, Code CEO, applauded Buck’s work. “Jana’s drive and dedication are significant factors in Code’s growth, and we are excited to watch her continue to shine in this new role.” Hansen also added, “Jana’s efforts on behalf of Code are part of what makes this a company our customers want to continue doing business with.”</p></blockquote><h4><strong>About Code</strong></h4><p>For over 20 years, Code has been&nbsp;an industry pioneer, leader, and champion for data capture innovation. By crafting and continuing to perfect its unique decoding algorithms, Code’s scanning technology consistently delivers unparalleled, image-based scanning and decoding performance industries depend on worldwide. Code designs and manufactures a complete line of market-leading data capture solutions that include both hardware and software products.</p><p>Code products are not only valued for providing a consistent level of workflow efficiency year after year, but also for their ergonomic design, durability, ease of customization, and seamless integration.</p>',
                'excerpt' => 'Jana served most recently as Code\'s VP of Operations. She has been with Code for 17 years. Before joining Code, Jana studied Pre-Med at Brigham Young University in Provo, Utah...',
                'meta_title' => 'Jana Buck Promoted To Code Corporations Chief Oper...',
                'meta_description' => 'Code Corporation announced recently that Jana Buck has been promoted to Chief Operations Officer. Sh...',
                'facebook_title' => 'Jana Buck Promoted To Code Corporations Chief Operations Officer on Facebook',
                'facebook_desc' => 'Code Corporation announced recently that Jana Buck has been promoted to Chief Operations Officer. Sh...',
                'twitter_post_description' => 'Code Corporation announced recently that Jana Buck has been promoted to Chief Operations Officer. Sh...',
                'twitter_post_title' => 'Jana Buck Promoted To Code Corporations Chief Operations Officer on Twitter',
                'published' => 1,
                'slug' => 'jana-buck-promoted-to-code-corporations-chief-operations-officer',
                'contributor' => NULL,
                'contributor_link' => NULL,
                'contributor_2' => NULL,
                'contributor_2_link' => NULL,
                'created_at' => '2019-11-22 21:44:53',
                'updated_at' => '2020-08-04 20:44:40',
                'deleted_at' => NULL,
                'status_id' => NULL,
                'author_id' => 21,
            ),
            10 => 
            array (
                'id' => 11,
                'title' => 'Code Names Bruce Scharf as Vice President of Product',
                'page_text' => '<figure class="image image-style-side"><img src="/storage/578/bruce-300x300.png"></figure><p><strong>Salt Lake City - January 22, 2020 —</strong> <a href="https://cts.businesswire.com/ct/CT?id=smartlink&amp;url=http%3A%2F%2Fwww.codecorp.com&amp;esheet=52161967&amp;newsitemid=20200122005540&amp;lan=en-US&amp;anchor=Code+Corporation&amp;index=1&amp;md5=3718c83ff6127747a40f1acb8a8d6461">Code Corporation</a> today announced the appointment of Bruce Scharf as Vice President of Product. In this role, Scharf will be responsible for setting strategy, scaling product teams and developing the roadmap for future Code products, markets and technologies.</p><p>“Bruce’s experience in innovating, building teams and product design in a rapidly evolving marketplace will be a tremendous asset to Code,” said Kent Hansen, CEO of Code Corporation. “We have an incredibly bright future and I am very pleased to bring on such a visionary leader with the skill, technical knowledge and industry passion to meet the needs of our growing customer base by bringing more cutting-edge products and solutions to life.”</p><p>Scharf has more than 20 years of experience in the data capture industry and has secured numerous patents. Prior to Code, he was vice president of engineering at Microscan where he led the research and development for track, trace and control solutions in life sciences, electronics and automotive markets. He lead a team of more than 40 engineers, scientists and technicians occupied in software, electrical, mechanical and optical design.</p><p>“Code is in an enviable market position due in no small part to the fact that we win the vast majority of business when we go head-to-head with any of our competition,” Scharf said. “The prospect of charting future markets and developing new technologies to grow Code is what makes this exciting. This company has a winning formula with its collaborative culture and talented team of global experts in both software and hardware. I can’t wait to turn them loose on new markets, customers and opportunities.”</p><h4><strong>About Code</strong></h4><p>For more than 20 years, Code Corporation has been an industry pioneer, leader, and champion for data capture innovation and has garnered more than 100 patents. By crafting and continuing to perfect its unique decoding algorithms, Code’s image-based scanning and decoding technology consistently delivers unparalleled performance that companies around the world depend on every day. Code designs and manufactures a complete line of market-leading hardware and software data capture solutions. Code products are not only valued for providing a consistent level of workflow efficiency year after year, but also for their ergonomic design, durability, ease of customization, and seamless integration. For more, please visit <a href="https://cts.businesswire.com/ct/CT?id=smartlink&amp;url=http%3A%2F%2Fwww.codecorp.com&amp;esheet=52161967&amp;newsitemid=20200122005540&amp;lan=en-US&amp;anchor=www.codecorp.com&amp;index=2&amp;md5=1e97b575ac5b2e47e7189e0b4df1d8cc">codecorp.com</a>.</p>',
                'excerpt' => 'As Vice President of Product, Scharf will be responsible for setting strategy, scaling product teams and developing the roadmap for future products, markets and technologies.“Bruce’s experience in innovating, building teams and product design in a rapidly evolving...',
                'meta_title' => 'Code Names Bruce Scharf as Vice President of Produ...',
                'meta_description' => 'Code Corporation today announced the appointment of Bruce Scharf as Vice President of Product.',
                'facebook_title' => 'Code Names Bruce Scharf as Vice President of Product on Facebook',
                'facebook_desc' => 'Code Corporation today announced the appointment of Bruce Scharf as Vice President of Product.',
                'twitter_post_description' => 'Code Corporation today announced the appointment of Bruce Scharf as Vice President of Product.',
                'twitter_post_title' => 'Code Names Bruce Scharf as Vice President of Product on Twitter',
                'published' => 1,
                'slug' => 'code-names-bruce-scharf-as-vice-president-of-product',
                'contributor' => NULL,
                'contributor_link' => NULL,
                'contributor_2' => NULL,
                'contributor_2_link' => NULL,
                'created_at' => '2020-01-22 21:45:35',
                'updated_at' => '2020-08-04 20:41:43',
                'deleted_at' => NULL,
                'status_id' => NULL,
                'author_id' => 21,
            ),
            11 => 
            array (
                'id' => 12,
                'title' => 'Rush University Medical Center Soft-Scanning First Adopter',
                'page_text' => '<p><strong>Salt Lake City, UT – March 21, 2018 —</strong> Code, a healthcare industry innovator and leader in image-based barcode scanning technology, is adding to its impressive, market-leading healthcare product portfolio with an industry first, “mobile HIS barcode soft-scanning”. Code is excited to announce that <a href="https://www.rush.edu/">Rush University Medical Center,</a> the Chicago-based five-star CMS rated academic medical center, is the first hospital system in the world to use CortexDecoder for Epic Rover. &nbsp;Rush began using the technology this month.</p><p><a href="https://www.codecorp.com/software/">Code’s CortexDecoder is a soft-scanning solution</a> that was chosen for integration into Epic Rover. It provides users enterprise-grade, barcode scanning strength – using only the camera on an iOS device. CortexDecoder can scan over 40 different barcode symbologies, allowing healthcare workers to seamlessly move from one workflow to another.</p><p>This new enterprise barcode scanning feature is a long-awaited workflow solution and Rush is excited to leverage this new technology. &nbsp;Software-enabled barcode scanning of patient wristbands to access medical records coupled with the ability to scan and verify medications helps to eliminate errors and improve patient safety – making soft-scanning a huge win for both the medical staff and their patients.</p><p>“CortexDecoder for Epic Rover enables Rush to use the five rights of medication administration: right patient, right medication, right dose, and right route at the right time.&nbsp; This technology will help to reduce the chance of medication harm and decrease the cost of care – which are pillars in achieving the Quadruple Aim”, says Dr. Shafiq Rab, Chief Information Officer of Rush.</p><p>The regional-focused Quadruple Aim initiative is based on a core belief that solutions to national problems, like healthcare, can be found and designed at local levels. For the individual healthcare consumer, this translates to outcomes of better culture, better care, better health, and lower costs.</p><p>“CortexDecoder reduces the need for cumbersome handheld devices carried by nurses, helping us achieve another pillar of the Quadruple Aim: improving the work life of healthcare providers, clinicians and staff, known as&nbsp;<a href="https://www.mihia.org/index.php/provider-well-being">Provider Well-Being</a>”, says Lisa Swiontek, Associate Vice President, Clinical Information Systems at Rush.</p><p>“We are excited to be working with Rush on this first adoption and rollout of soft-scanning,” said Garrett Russell, Vice President of Sales and Marketing for Code. “The healthcare industry has been waiting for the next ‘big thing’ and combining CortexDecoder with Epic Rover is it. This is a huge step for the industry, and Rush is at the forefront of this mobility revolution.”</p><h4><strong>About Code</strong></h4><p>Code&nbsp;is a technology leader in image-based barcode reading solutions. Code designs and manufactures a complete line of image-based barcode reading hardware and software solutions to enhance productivity and exceed customers’ expectations for superior barcode reading performance, ergonomic design, equipment durability, and seamless integration with their operations. Servicing a diverse range of industries and environments, Code’s products are used in critical applications in healthcare, public safety, manufacturing, transportation, retail, and a range of other diverse industries.</p><p>Code\'s worldwide headquarters are located in Salt Lake City, USA, and has regional headquarters in China, Singapore, and The Netherlands.</p><h4><strong>About Rush</strong></h4><p>Rush is an academic health system whose mission is to improve the health of the patients and the diverse communities it serves with nationally recognized health care, education, research and a commitment to community partnerships. The Rush system comprises Rush University Medical Center, Rush University, Rush-Copley Medical Center and Rush Oak Park Hospital, as well as numerous outpatient care facilities. Rush University, with more than 2,500 students, is a health sciences university that comprises Rush Medical College, the College of Nursing, the College of Health Sciences and the Graduate College.</p>',
                'excerpt' => 'Rush University Medical Center becomes first to adopt Code\'s industry-first mobile HIS barcode soft-scanning solution...',
                'meta_title' => 'Rush University Medical Center Soft-scanning First Adopter',
                'meta_description' => 'Code is excited to announce that Rush University Medical Center is the first hospital system in the world to use CortexDecoder for Epic Rover.',
                'facebook_title' => 'Rush University Medical Center Soft-scanning First Adopter on Facebook',
                'facebook_desc' => 'Code is excited to announce that Rush University Medical Center is the first hospital system in the world to use CortexDecoder for Epic Rover.',
                'twitter_post_description' => 'Code is excited to announce that Rush University Medical Center is the first hospital system in the world to use CortexDecoder for Epic Rover.',
                'twitter_post_title' => 'Rush University Medical Center Soft-scanning First Adopter on Twitter',
                'published' => 1,
                'slug' => 'rush-university-medical-center-soft-scanning-first-adopter',
                'contributor' => NULL,
                'contributor_link' => NULL,
                'contributor_2' => NULL,
                'contributor_2_link' => NULL,
                'created_at' => '2018-03-21 17:29:38',
                'updated_at' => '2020-08-04 20:40:22',
                'deleted_at' => NULL,
                'status_id' => NULL,
                'author_id' => 21,
            ),
            12 => 
            array (
                'id' => 13,
                'title' => 'Code releases powered protection for iPhone 7 & 8',
            'page_text' => '<figure class="image image-style-side"><img src="https://camo.githubusercontent.com/1a122a9de18688bca53d0259f8ba819e0d0cef78/68747470733a2f2f7777772e636f6465636f72702e636f6d2f77702d636f6e74656e742f75706c6f6164732f323032302f30362f4352373031382d436c65616e696e672d50686f746f2d574542534954452d50524f445543542d504147452d333030783231372e6a7067" alt="CR7018 Cleaning Photo WEBSITE PRODUCT PAGE"></figure><p><strong>Salt Lake City, UT - February 11, 2019 –</strong> Code, an innovator in healthcare automation and mobile technology, is bringing some additional excitement to the Healthcare Information Management Systems Society (HIMSS) show in Orlando with the release of the CR7000 series healthcare mobile battery case.&nbsp; The durable protector for the iPhone® 7 and 8 completely shields your valuable electronics while maximizing uptime with its quick-swappable battery, all in a compact package made to stand up to the toughest disinfecting chemicals.</p><p>“Health systems should be able to take full advantage of the benefits of mobile devices without having to sacrifice efficiency or infection control,” said George Powell, CEO and President of Code.&nbsp; “With the ruggedness and extra power of the CR7018, hospitals can recognize the full potential of a mobile workforce.”</p><figure class="image image-style-side"><img src="https://camo.githubusercontent.com/6a2b6400221f0b5c0b75022ffabe057ca99e7332/68747470733a2f2f7777772e636f6465636f72702e636f6d2f77702d636f6e74656e742f75706c6f6164732f323032302f30362f4352373031382d6375742d6f75742d6261636b2d7765622e706e67" alt="CR7018 cut out back web"></figure><p>Constructed with market-leading CodeShield® plastics and Dragontrail™ glass, <a href="https://github.com/ap-coder/tojekyll/blob/master/portfolio-items/code-reader-7018">the CR7018 completely safeguards the iPhone 7 and 8 in an IP54-sealed enclosure.</a>&nbsp; The quick-swap battery more than doubles the runtime of the iPhone, with a built-in gauge to let nurses know when it’s time to grab more power.&nbsp; With the push of a button, they can easily exchange for a fully-charged battery from one of Code’s enterprise chargers, all without removing the iPhone from the protective case.&nbsp; Users can rapidly charge up to 10 batteries at a time so full power is always on-hand, and a variety of mounting configurations means chargers are easily accessible wherever they are needed.</p><p>The CR7018 also comes with the essential tools that hospital IT needs for easy device management.&nbsp; BatteryTrak™ gives administrators visibility to the age of their batteries and helps them plan appropriately for replacements.&nbsp; <i>Code Complete</i>™ provisioning and deployment services are also available to help reduce the strain on internal resources.</p><p>“As hospitals roll out their iPhone clinical communication strategy, they’ve typically settled for flimsy consumer cases to provide some level of protection to their investment,” said Jennifer Braun, Mobile Program Manager. &nbsp;“Code has packaged decades of healthcare technology know-how into the CR7018, so now hospitals don’t have to settle.”</p>',
                'excerpt' => 'Code releases the CR7000 series healthcare mobile battery at the HIMSS show in Orlando. The durable protector for iPhone 7 and 8 completely shields valuable electronics while...',
                'meta_title' => 'Healthcare Battery Case For Iphone® Has Arrived',
                'meta_description' => 'Code releases the CR7000 series healthcare mobile battery case...',
                'facebook_title' => 'Healthcare Battery Case For Iphone® Has Arrived on Facebook',
                'facebook_desc' => 'Code releases the CR7000 series healthcare mobile battery case...',
                'twitter_post_description' => 'Code releases the CR7000 series healthcare mobile battery case...',
                'twitter_post_title' => 'Healthcare Battery Case For Iphone® Has Arrived on Twitter',
                'published' => 1,
                'slug' => 'code-releases-powered-protection-for-iphone-7-8',
                'contributor' => NULL,
                'contributor_link' => NULL,
                'contributor_2' => NULL,
                'contributor_2_link' => NULL,
                'created_at' => '2019-02-11 08:00:11',
                'updated_at' => '2020-08-04 23:19:02',
                'deleted_at' => NULL,
                'status_id' => NULL,
                'author_id' => 21,
            ),
            13 => 
            array (
                'id' => 14,
                'title' => 'Duplicate 2',
            'page_text' => '<h2><strong>CR1100 Makes It Easy to Integrate Barcode Scanning</strong></h2><p>Salt Lake City, UT - February 6, 2019 – Code, an innovator in healthcare automation and mobile technology, is featuring its new <a href="https://www.codecorp.com/portfolio_category/manufacturing/">CR1100</a> compact barcode reading system at the Health Information Management Systems Society (HIMSS) show in Orlando next week. The CR1100 features years of healthcare barcode reading experience combined with the latest image processing technology in a tiny package that easily fits into a variety of medical devices.</p><p><i><strong>“The CR1100 is different than most embedded barcode readers because it gives full scanner functionality – reading, audible feedback, plug-and-play interface cables – in the smallest product possible,” said Garrett Russell, Vice President of Marketing and North American Sales. “Manufacturers have enough to worry about with their own technology, so we made ours stress free for them to integrate.”</strong></i></p><p>For nearly 20 years, Code has dealt with the toughest scanning challenges in hospitals, pharmacies, and labs, reading even the most damaged barcodes when no one else could. This specialized knowledge has been combined with patented functionality to create the CR1100: a reader well suited for healthcare applications.</p><p>Code has taken additional steps to shrink the footprint of the technology without sacrificing performance. The result is a fully enclosed, super small scanner with integrated mounting features and plug-and-play interface cables to allow medical device manufacturers to add barcode reading functionality to their systems quickly. A powerful JavaScript platform makes it easy to customize the CR1100 to interface with virtually any host.</p><p><i><strong>“Code has a long history of working closely with device manufacturers to optimize data capture,” said Hong Ji, Program Manager. “The CR1100 continues our dedication to providing flexible solutions for these customers without having them settle for less than the best reading performance.”</strong></i></p><p><strong>How can we help your business succeed?</strong></p>',
            'excerpt' => 'CR1100 Makes It Easy to Integrate Barcode Scanning Code, an innovator in healthcare automation and mobile technology, is featuring its new CR1100 compact barcode reading system at the Health Information Management Systems Society (HIMSS) show in Orlando next week. The CR1100 features years of healthcare barcode reading experience combined with...',
                'meta_title' => 'Medical Device Manufacturers: We Hear You!',
                'meta_description' => 'CR1100 Makes It Easy to Integrate Barcode Scanning',
                'facebook_title' => 'Medical Device Manufacturers: We Hear You! on Facebook',
                'facebook_desc' => 'CR1100 Makes It Easy to Integrate Barcode Scanning',
                'twitter_post_description' => 'CR1100 Makes It Easy to Integrate Barcode Scanning',
                'twitter_post_title' => 'Medical Device Manufacturers: We Hear You! on Twitter',
                'published' => 1,
                'slug' => 'duplicate-2',
                'contributor' => NULL,
                'contributor_link' => NULL,
                'contributor_2' => NULL,
                'contributor_2_link' => NULL,
                'created_at' => '2019-02-04 21:06:21',
                'updated_at' => '2020-08-03 23:40:12',
                'deleted_at' => '2020-08-03 23:40:12',
                'status_id' => 1,
                'author_id' => 21,
            ),
            14 => 
            array (
                'id' => 15,
                'title' => 'Code Moves to New Digs',
                'page_text' => '<p><strong>Salt Lake City, Utah – December 16, 2019 —</strong> Code Corporation, a leading innovator in the barcode scanning industry, has moved its U.S. headquarters to a new location. The new address for the company is 434 West Ascension Way, Suite 300, Murray, Utah 84123. All other company information, such as phone numbers and emails, remains the same.</p><p>The new office is located in the center of the Salt Lake Valley. The space will allow for better collaboration between teams as well as providing a more modern, efficient workspace. Code CEO Kent Hansen said, “We are excited about this beautiful, new location and the opportunities it affords us to grow as an organization. We look forward to enjoying this impressive space, and we are grateful to the employees who worked so hard to pull this move together.”</p><h4><strong>About Code</strong></h4><p>Code&nbsp;is a technology leader in data capture solutions and mobile technology. Code designs and manufactures a complete line of hardware and software solutions to enhance productivity and exceed customers’ expectations for superior barcode reading performance, ergonomic design, equipment durability, and seamless integration with their operations. Servicing a diverse range of industries and environments, Code’s products are used in critical applications in healthcare, public safety, manufacturing, transportation, retail, and a range of other diverse industries.</p><p>Code\'s worldwide headquarters are located in Murray, USA, with regional headquarters in the Netherlands. For more information, visit&nbsp;<a href="http://www.codecorp.com/">codecorp.com</a>.</p><p>Media Contact:<br>Garrett Russell, VP Sales, Americas &amp; Global Marketing<br>Email:&nbsp;<a href="mailto:garrett.russell@codecorp.com">garrett.russell@codecorp.com</a></p>',
            'excerpt' => 'Code moves U.S. headquarters to Murray, UT (Salt Lake City metropolitan area). Company information other than address remains the same. The new office is...',
                'meta_title' => 'Code Moves to New Digs',
                'meta_description' => 'Code Corporation, a leading innovator in the barcode scanning industry, has moved its U.S. headquarters to a new...',
                'facebook_title' => 'Code Moves to New Digs on Facebook',
                'facebook_desc' => 'Code Corporation, a leading innovator in the barcode scanning industry, has moved its U.S. headquarters to a new...',
                'twitter_post_description' => 'Code Corporation, a leading innovator in the barcode scanning industry, has moved its U.S. headquarters to a new...',
                'twitter_post_title' => 'Code Moves to New Digs on Twitter',
                'published' => 1,
                'slug' => 'code-moves-to-new-digs',
                'contributor' => NULL,
                'contributor_link' => NULL,
                'contributor_2' => NULL,
                'contributor_2_link' => NULL,
                'created_at' => '2019-12-16 20:35:11',
                'updated_at' => '2020-08-04 20:20:40',
                'deleted_at' => NULL,
                'status_id' => 1,
                'author_id' => 23,
            ),
            15 => 
            array (
                'id' => 16,
                'title' => 'Code Again Ranks in Top 20 for Patents Issued in Utah',
                'page_text' => '<h4><strong>Code Reinforces its Place Among the State’s Technological Elite</strong></h4><figure class="image image-style-side"><img src="https://camo.githubusercontent.com/9e6e968ac86908e7730164417a40f51a3880ca48/68747470733a2f2f7777772e636f6465636f72702e636f6d2f77702d636f6e74656e742f75706c6f6164732f323032302f30362f706174656e74732d333030783139322e706e67" alt="patents"></figure><p>Salt Lake City, UT – April 19, 2019 – Code, an innovator in healthcare automation and mobile technology, was honored at the 2019 Utah Genius Awards for the number of patents issued during the 2018 calendar year. <strong>It is the third straight year Code has been recognized for key contributions in driving Utah’s creative economy</strong>.</p><p>Utah Genius was founded in 2009 to acknowledge and celebrate the Beehive State’s most innovative companies. Awards recognize Utah’s Top 20 Companies by Number of Patents Issued, Top 20 Inventors, and Top 10 Trademark Registrants based on objective statistics from the U.S. Patent and Trademark Office.</p><p>Code was distinguished as a 2018 Top 20 Company by Number of Patents Issued during 2017, earning 19 from the U.S. Patent and Trademark Office. Code’s President and CEO, George Powell, and Vice President of Engineering, Ryan Hoobler, were also recognized as Top 20 Patentees. The previous year, Code was granted 13 patents, also resulting in a Top 20 finish.</p><p>“Our driving passion at Code is to continually innovate and revolutionize in ways that don’t just advance, but transcend,” said George Powell, President and CEO at Code. “Being honored three years in a row by Utah Genius for those intellectual property achievements is a testament to the Code team’s tireless dedication to developing the most forward-thinking and cutting edge products in the marketplace.”</p><h4><strong>About Code</strong></h4><p>Code is a technology leader in data capture solutions and mobile technology. Code designs and manufactures a complete line of hardware and software solutions to enhance productivity and exceed customers’ expectations for superior barcode reading performance, ergonomic design, equipment durability, and seamless integration with their operations. Servicing a diverse range of industries and environments, Code’s products are used in critical applications in healthcare, public safety, manufacturing, transportation, retail, and a range of other diverse industries.</p><p>Have questions or want to take a look at our award winning data capture technology? We would love to share it with you! Let\'s chat.</p>',
                'excerpt' => 'Code was honored at the 2019 Utah Genius Awards for the number of patents issued during the 2018 calendar year. It is the third straight year Code has been recognized for key contributions...',
                'meta_title' => 'CODE AGAIN RANKS IN TOP 20 FOR PATENTS ISSUED IN U...',
                'meta_description' => 'Code Reinforces Its Place Among the State’s Technological Elite',
                'facebook_title' => 'CODE AGAIN RANKS IN TOP 20 FOR PATENTS ISSUED IN UTAH on Facebook',
                'facebook_desc' => 'Code Reinforces Its Place Among the State’s Technological Elite',
                'twitter_post_description' => 'Code Reinforces Its Place Among the State’s Technological Elite',
                'twitter_post_title' => 'CODE AGAIN RANKS IN TOP 20 FOR PATENTS ISSUED IN UTAH on Twitter',
                'published' => 1,
                'slug' => 'code-again-ranks-in-top-20-for-patents-issued-in-utah',
                'contributor' => NULL,
                'contributor_link' => NULL,
                'contributor_2' => NULL,
                'contributor_2_link' => NULL,
                'created_at' => '2019-04-29 15:07:42',
                'updated_at' => '2020-08-04 20:07:27',
                'deleted_at' => NULL,
                'status_id' => 1,
                'author_id' => 23,
            ),
            16 => 
            array (
                'id' => 17,
                'title' => 'Code Corporation’s Miniature Image Scan Engine Brings New Capabilities to Life Science',
                'page_text' => '<p><strong>Salt Lake City - April 10, 2020 —</strong> Code Corporation today announced it has updated its OEM series of high-performance, miniature image scan engines. Code’s CR8200 product line now boasts powerful image enhancement controls to improve the efficiency and accuracy of automated life science instruments.</p><figure class="image image-style-side"><img src="https://camo.githubusercontent.com/70472d0f0f660976e3b8e2ff0f99b9125866c840/68747470733a2f2f7777772e636f6465636f72702e636f6d2f77702d636f6e74656e742f75706c6f6164732f323032302f30342f74696e792d7363616e6e6572732d333030783137382e6a7067" alt="tiny scanners"></figure><p>As the demand for smaller size, lower cost and higher throughput machines grows, the challenge to fortify accuracy in assay results becomes imperative. Industry leaders are turning to digital imaging experts to solve this problem and companies such as Code are heeding the call.</p><p>In a lab setting, test tube, lateral flow and microfluidic devices all require visual methods to measure, track and automate results. Within these environments, however, exist a unique myriad of obstacles to overcome. Unevenly lit scenes, multiple targets and varying focal planes are just a few of the hurdles in the gauntlet; to extract a good image requires an exceptional set of tools.</p><p>In its most recent update, Code introduced fully customizable sub-image “attention” areas to create automated setpoints for image brightness and contrast. Cropping, windowing and field selection have also been enhanced in such a way to add “layers” of customizable permutations to attain the best image possible. Coupled with patented dual-field optics and world-leading barcode decoder, the CR8200 OEM engine gives the end user total flexibility in their implementation.</p><p>“The innovative image capture capabilities we have added to the CR8200 are further helping clinical labs reduce risk, increase efficiencies, and provide better outcomes,” said Kent Hansen, CEO of Code Corporation. “By tightly controlling and optimizing the image capture process with brightness and contrast of the specific area of interest, the CR8200 performs beyond industry norms for what is expected of a barcode reader engine, and transfers that leap in efficiency and performance onto our clients.”</p><p>These updates were included in the firmware release version 1.16.0 which provided additional, advanced image capture capabilities to its industry-leading high performance imaging. With rapid, first-pass read rates, the CR8200 effortlessly decodes 1D, 2D, postal, and direct part mark barcodes printed on a variety of surfaces in a variety of conditions. Applications include use in medical devices, kiosks, ATMs, manufacturing, direct part marking, handheld devices, mobile computers and more. For more information, please visit <a href="https://www.codecorp.com/portfolio-items/scan-engines/">https://www.codecorp.com/portfolio-items/scan-engines/</a>.</p><h4><strong>About Code Corporation</strong></h4><p>For more than 20 years, Code Corporation has been an industry pioneer, leader, and champion for data capture innovation and has garnered more than 100 patents. By crafting and continuing to perfect its unique decoding algorithms, Code’s image-based scanning and decoding technology consistently delivers unparalleled performance companies around the world depend on every day. Code designs and manufactures a complete line of market-leading hardware and software data capture solutions. Code products are not only valued for providing a consistent level of workflow efficiency year after year, but also for their ergonomic design, durability, ease of customization, and seamless integration. For more, please visit <a href="http://www.codecorp.com/">codecorp.com</a>.</p><p><strong>Contact</strong>:<br>Tim Rush Springboard5 801-208-1100 <a href="mailto:tim.rush@springboard5.com">tim.rush@springboard5.com</a></p>',
                'excerpt' => 'This addition to the OEM series of high-performance, miniature image scan engines boasts powerful image enhancement controls to improve efficiency and accuracy of automated life science instruments...',
                'meta_title' => 'Code Corporation’s Miniature Image Scan Engine Bri...',
            'meta_description' => 'SALT LAKE CITY--(BUSINESS WIRE)--Code Corporation today announced it has updated its OEM series of h...',
                'facebook_title' => 'Code Corporation’s Miniature Image Scan Engine Brings New Capabilities to Life Science on Facebook',
            'facebook_desc' => 'SALT LAKE CITY--(BUSINESS WIRE)--Code Corporation today announced it has updated its OEM series of h...',
            'twitter_post_description' => 'SALT LAKE CITY--(BUSINESS WIRE)--Code Corporation today announced it has updated its OEM series of h...',
                'twitter_post_title' => 'Code Corporation’s Miniature Image Scan Engine Brings New Capabilities to Life Science on Twitter',
                'published' => 1,
                'slug' => 'code-corporations-miniature-image-scan-engine-brings-new-capabilities-to-life-science',
                'contributor' => NULL,
                'contributor_link' => NULL,
                'contributor_2' => NULL,
                'contributor_2_link' => NULL,
                'created_at' => '2020-04-20 15:26:57',
                'updated_at' => '2020-08-04 20:04:38',
                'deleted_at' => NULL,
                'status_id' => 1,
                'author_id' => 23,
            ),
            17 => 
            array (
                'id' => 18,
                'title' => 'Code Releases DotCode Scanning Algorithm in Support of Tobacco Products Directive',
            'page_text' => '<h4><strong>TachyonIQ Releases DotCode Scanning Algorithm in Support of Tobacco Products Directive</strong></h4><p>(NOTE: Former subsidiary TachyonIQ has merged with Code Corporation)</p><p>TachyonIQ, the leader in image processing software for data capture, announced the release of a new barcode scanning algorithm that omnidirectionally decodes the mandatory DotCode barcode symbology of the EU Tobacco Products Directive.</p><p>The European tobacco industry, with other industries following suit, has adopted systems for the traceability of products throughout the supply chain. By imprinting a unique DotCode barcode on tobacco product packaging, manufacturers and retailers are able to track and report product movement and help stop the illegal smuggling and counterfeiting of cigarettes and fine-cut products.</p><figure class="image image-style-side"><img src="//www.tachyoniq.com/wp-content/uploads/2019/06/DotCodeOnCigPack-PhotoDomino_1000x640-300x192.jpg" alt="DotCode scans accurately using TachyonIQ decoders"><figcaption>&nbsp;Photo courtesy of Domino Packaging</figcaption></figure><p>Consumers also benefit from the Track and Trace systems, a name aptly given to the traceability of products, according to the EU Commission, as it provides precise identification of all packaging and ensures a high level of health protection for European citizens.</p><p><strong>The DotCode barcode utilizes a 2D symbol that allows for more information to be embedded in a substantially smaller amount of space.</strong> "Other 2D barcode symbologies exist," says Thomas Rissmann, TachyonIQ EMEA Sales Manager, "but the DotCode symbology was developed to allow for high-speed printing applications associated with product manufacturing. Our decoder has proven to be forgiving—even in omnidirectional reading—should clogged ink jets, line speed, and other printing problems occur during manufacturing and packaging."</p><p><strong>The TachyonIQ algorithm instantly and accurately decodes the DotCode symbols</strong> in spite of printing problems, shrink-wrap films, low contrast backgrounds, or even worn or damaged codes. The software is used worldwide in handheld scanners from Code Corporation, often at the retail point-of-sale and in warehousing, distribution, and the manufacturing plant floor, thus enabling the Track and Trace systems to capture the data needed for the EU Directive.</p><figure class="image image-style-side"><img src="https://www.tachyoniq.com/wp-content/uploads/2019/06/DotCode-Sample-ShutterstockImage-300x64.png" alt="CortexDecoder scans DotCode symbology"><figcaption>&nbsp;Example of DotCode barcode symbology</figcaption></figure><p>In its mission to provide the most accurate and highest quality barcode decoding algorithms, TachyonIQ adds the DotCode symbology to its list of <a href="https://www.tachyoniq.com/2d-difference/">40-plus supported barcodes</a>. The symbology decoder is included in the TachyonIQ EdgeDecoder™ software developers kit (SDK), providing easy to implement capabilities to software engineers worldwide who are developing anti-counterfeiting and authentication initiatives to combat the growing problem of counterfeiting found in the pharmaceutical, automotive, fashion, consumer electronics, and tobacco industries.</p><p>&nbsp;</p><p>&nbsp;</p>',
                'excerpt' => 'The new barcode scanning algorithm omnidirectionally decodes the DotCode symbology of the EU Tobacco Products Directive. The European tobacco industry, with other industries...',
                'meta_title' => 'Code Releases DotCode Scanning Algorithm in Suppor...',
                'meta_description' => 'Code Corporation Releases DotCode Scanning Algorithm in Support of Tobacco Products Directive...',
                'facebook_title' => 'Code Releases DotCode Scanning Algorithm in Support of Tobacco Products Directive on Facebook',
                'facebook_desc' => 'Code Corporation Releases DotCode Scanning Algorithm in Support of Tobacco Products Directive...',
                'twitter_post_description' => 'Code Corporation Releases DotCode Scanning Algorithm in Support of Tobacco Products Directive...',
                'twitter_post_title' => 'Code Corporation Releases DotCode Scanning Algorithm in Support of Tobacco Products Directive...',
                'published' => 1,
                'slug' => 'code-releases-dotcode-scanning-algorithm-in-support-of-tobacco-products-directive',
                'contributor' => 'Doug Coats',
                'contributor_link' => NULL,
                'contributor_2' => NULL,
                'contributor_2_link' => NULL,
                'created_at' => '2019-06-06 21:12:22',
                'updated_at' => '2020-08-04 20:02:28',
                'deleted_at' => NULL,
                'status_id' => 1,
                'author_id' => 23,
            ),
        ));
        
        
    }
}